// openprint/src/design/canvas/CellToolbar.vue
<script setup lang="ts">
/**
 * CellToolbar —— 单元格浮动工具栏（方案 A）
 *
 * 双击进入单元格后浮在其上方，提供 ERP 报表最常用的单元格级能力：
 * 字段绑定 / 字体族 / 字号 / 加粗斜体下划线 / 水平垂直对齐 / 文字色 / 填充色 / 横向合并 / 清除样式。
 *
 * 本组件**不直接改 store**：所有动作算出「新的表格控件」后 emit('apply')，
 * 由 TableViewLayer 统一写回并刷新 overlay —— 保持单一写入口，撤销栈干净。
 */
import { computed, ref } from 'vue'
import {
  NButton,
  NButtonGroup,
  NColorPicker,
  NDivider,
  NInput,
  NInputNumber,
  NSwitch,
  NSelect,
  NTooltip,
} from 'naive-ui'
import type { SelectOption, SelectGroupOption } from 'naive-ui'
import type { TableCell, TableCellStyle, TableControl, CellFormat, CellFormatKind } from '@/types/control'
import {
  buildDesignGrid,
  insertTableColumn,
  insertTableRow,
  patchCell,
  patchCellStyle,
  removeTableColumn,
  removeTableRow,
  resolveCellStyle,
  rowRoleLabel,
  setCellRowSpan,
  setCellSpan,
} from '@/core/layout-engine/table-cells'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '@/design/composables/useSystemFonts'
import { useDataSourceStore } from '@/design/stores/dataSource'
import ContentValueEditor from '@/design/panels/props/ContentValueEditor.vue'
import type { ContentMode } from '@/design/panels/props/ContentValueEditor.vue'
import ExpressionModal from '@/design/panels/props/ExpressionModal.vue'
import {
  formatKindOptions,
  datePatternOptions,
  currencyCodeOptions,
  makeFormat,
  needsPattern,
  needsDigits,
  needsCode,
  supportsThousands,
} from '@/design/format-options'

const props = defineProps<{
  control: TableControl
  row: number
  col: number
  /** 行语义：header=表头 / data=数据样例行（影响整列）/ static=静态行 */
  rowKind: 'header' | 'data' | 'static'
  x: number
  y: number
}>()

const emit = defineEmits<{
  (e: 'apply', next: TableControl): void
  (e: 'close'): void
}>()

const ds = useDataSourceStore()

const grid = computed(() => buildDesignGrid(props.control))
const cell = computed<TableCell>(() => grid.value.cells[props.row]?.[props.col] ?? {})
const column = computed(() => props.control.columns[props.col])
const style = computed<TableCellStyle>(() => resolveCellStyle(props.control, column.value, cell.value))

const sysFonts = useSystemFonts()

const fontOptions = computed<(SelectOption | SelectGroupOption)[]>(() => {
  const builtin: SelectOption[] = [
    { label: '默认', value: '' },
    ...FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })),
  ]
  if (!sysFonts.ready.value) return builtin
  const sysOpts: SelectOption[] = sysFonts.grouped.value.map((g) => ({ label: g.family, value: g.family }))
  return [
    { type: 'group', label: '预设字体', key: 'builtin', children: builtin.filter((o) => o.value !== '') },
    { type: 'group', label: `电脑系统字体（${sysFonts.count.value}）`, key: 'system', children: sysOpts },
    { label: '默认', value: '' },
  ]
})

/**
 * 可绑定字段（用于变量模式默认值）：
 * - 数据样例行 → 明细表（数组）字段，运行期按行迭代
 * - 表头 / 静态行 → 主表标量字段
 */
const detailFields = computed(() => {
  const isDetail = props.rowKind === 'data'
  const tables = ds.activeSource?.tables ?? []
  const arrayTableIds = new Set(tables.filter((t) => t.isArray).map((t) => t.id))
  return ds.flatFields.filter((f) => {
    const inArray = f.tableId ? arrayTableIds.has(f.tableId) : f.path.includes('[]')
    return isDetail ? inArray : !inArray
  })
})

/** 变量模式默认路径：取该行语义下的第一个字段（数据行=明细字段，其余=标量字段） */
const bindingDefault = computed(
  () => detailFields.value[0]?.path ?? (props.rowKind === 'data' ? 'items[].name' : 'order.orderNo'),
)

/** 表达式模式默认值（数据行按行迭代，其余按主表上下文） */
const expressionDefault = computed(() =>
  props.rowKind === 'data' ? '{{rowIndex + 1}}' : '{{order.total}}',
)

/** 单元格内容三态：固定值 / 变量（字段绑定） / 表达式（显式 contentType，老模板启发式回退） */
const cellMode = computed<ContentMode>(() => {
  const c = cell.value
  if (c?.contentType) return c.contentType
  return c?.expression ? 'expression' : c?.field ? 'variable' : 'fixed'
})

/** 模式切换：写 contentType + 清空其它两个字段（默认值由编辑器按 bindingDefault 注入） */
function onCellMode(m: ContentMode): void {
  const p: Partial<TableCell> = { contentType: m }
  if (m === 'fixed') {
    p.field = undefined
    p.expression = undefined
  } else if (m === 'variable') {
    p.expression = undefined
  } else {
    p.field = undefined
  }
  emit('apply', patchCell(props.control, props.row, props.col, p))
}

function onCellValue(v: string): void {
  emit('apply', patchCell(props.control, props.row, props.col, { text: v }))
}

/** 变量模式：写 contentType + field 并清空 text/expression，保证 field 为唯一取值源 */
function onCellBinding(path: string): void {
  emit(
    'apply',
    patchCell(props.control, props.row, props.col, {
      contentType: 'variable',
      field: path || undefined,
      text: undefined,
      expression: undefined,
    }),
  )
}

function onCellExpression(v: string): void {
  emit(
    'apply',
    patchCell(props.control, props.row, props.col, {
      contentType: 'expression',
      expression: v || undefined,
      text: undefined,
      field: undefined,
    }),
  )
}

/** 仅绑定了字段/表达式（或显式 variable/expression 模式）的单元格才需要格式（纯静态文字格式无意义） */
const canFormat = computed(
  () =>
    cell.value.contentType === 'variable' ||
    cell.value.contentType === 'expression' ||
    Boolean(cell.value.field || cell.value.expression) ||
    (props.rowKind === 'data' && Boolean(column.value?.field || column.value?.expression)),
)

/** 生效中的格式（单元格优先，回落列默认） */
const cellFormat = computed<CellFormat | undefined>(() => cell.value.format ?? column.value?.format)

/* --------------------------------- 动作 -------------------------------- */

function applyStyle(patch: TableCellStyle): void {
  emit('apply', patchCellStyle(props.control, props.row, props.col, patch))
}

/* ----- 动态配色：把 {{}} 表达式写入列级 columns[i].style ----- */
/** 文字色 / 填充色表达式弹窗显示态 */
const colorExprShow = ref(false)
const bgExprShow = ref(false)
/** 当前正在编辑的表达式初始值（从列级 style 回显） */
const colorExprInit = computed(() => column.value?.style?.color ?? '')
const bgExprInit = computed(() => column.value?.style?.backgroundColor ?? '')

/** 文字色 / 填充色是否处于「表达式模式」（值含 {{）—— 此时色块按钮显示 fx 占位 */
const isColorExpr = computed(() => /\{\{/.test(column.value?.style?.color ?? ''))
const isBgExpr = computed(() => /\{\{/.test(column.value?.style?.backgroundColor ?? ''))

/** 写入列级 style（columns[i].style），整列数据行生效 */
function applyColumnStyle(patch: TableCellStyle): void {
  const cur = column.value?.style ?? {}
  const merged: TableCellStyle = { ...cur }
  for (const [k, v] of Object.entries(patch)) {
    if (v === undefined) delete (merged as Record<string, unknown>)[k]
    else (merged as Record<string, unknown>)[k] = v
  }
  // 复用上层 patchColumn：构造新 columns 数组并 emit('apply')
  const columns = props.control.columns.map((c, i) =>
    i === props.col ? { ...c, style: merged } : c,
  )
  emit('apply', { ...props.control, columns })
}

function onColorExprConfirm(v: string): void {
  applyColumnStyle({ color: v || undefined })
}
function onBgExprConfirm(v: string): void {
  applyColumnStyle({ backgroundColor: v || undefined })
}

function toggle(key: 'bold' | 'italic' | 'underline'): void {
  applyStyle({ [key]: !style.value[key] } as TableCellStyle)
}

const spanMax = computed(() => grid.value.colCount - props.col)
const currentSpan = computed(() => Math.min(cell.value.colSpan ?? 1, spanMax.value))

function setSpan(n: number | null): void {
  emit('apply', setCellSpan(props.control, props.row, props.col, n ?? 1))
}

/**
 * 纵向合并（rowSpan）。
 * 仅表头 / 静态 / 布局网格行生效：数据行由运行期逐条生成，跨行会跨越不同记录，语义不成立，
 * 故数据样例行（rowKind==='data'）禁用该项，与表格引擎的"模板行强制 rowSpan=1"一致。
 */
const canRowSpan = computed(() => props.rowKind !== 'data')
const rowSpanMax = computed(() => grid.value.rowCount - props.row)
const currentRowSpan = computed(() => Math.min(cell.value.rowSpan ?? 1, rowSpanMax.value))

function setRowSpan(n: number | null): void {
  if (!canRowSpan.value) return
  emit('apply', setCellRowSpan(props.control, props.row, props.col, n ?? 1))
}

function clearStyle(): void {
  emit('apply', patchCell(props.control, props.row, props.col, { style: undefined }))
}

/** 单元格斜线（课表角标等）：无 / 左上→右下 / 左下→右上 */
const diagOptions = [
  { label: '无', value: 'none' },
  { label: '↘ 右下', value: 'down' },
  { label: '↗ 右上', value: 'up' },
]
const currentDiagonal = computed<'none' | 'down' | 'up'>(() => cell.value.style?.diagonal ?? 'none')
function setDiagonal(v: 'none' | 'down' | 'up'): void {
  applyStyle({ diagonal: v === 'none' ? undefined : v })
}

function applyFormat(fmt: CellFormat | undefined): void {
  // kind='none' 视为清除，避免脏字段
  emit('apply', patchCell(props.control, props.row, props.col, { format: fmt && fmt.kind !== 'none' ? fmt : undefined }))
}

function isPresetDatePattern(p?: string): boolean {
  return Boolean(p && datePatternOptions.some((o) => o.value !== '__custom__' && o.value === p))
}

/** 行角色名（标题行 / 数据行 / 本页合计行 / 总计行 / 大写金额行），用于工具栏标签 */
const roleLabel = computed(() => {
  if (props.rowKind === 'data') return '数据行（影响整列）'
  return rowRoleLabel(buildDesignGrid(props.control), props.row)
})

/* --------------------------------- 行列插入 -------------------------------- */

function insertRowAbove(): void {
  emit('apply', insertTableRow(props.control, props.row))
}

function insertRowBelow(): void {
  emit('apply', insertTableRow(props.control, props.row + 1))
}

function insertColLeft(): void {
  emit('apply', insertTableColumn(props.control, props.col))
}

function insertColRight(): void {
  emit('apply', insertTableColumn(props.control, props.col + 1))
}

/** 删除本行 / 本列（数据表的数据样例行不可删，由 canDeleteRow 收敛） */
const canDeleteRow = computed(
  () => props.rowKind !== 'data' && grid.value.rowCount > 1,
)
const canDeleteCol = computed(() => grid.value.colCount > 1)

function deleteRow(): void {
  emit('apply', removeTableRow(props.control, props.row))
}

function deleteCol(): void {
  emit('apply', removeTableColumn(props.control, props.col))
}
</script>

<template>
  <div
    class="op-cell-toolbar"
    :style="{ left: `${x}px`, top: `${y}px` }"
    @mousedown.stop
    @dblclick.stop
  >
    <div class="op-cell-toolbar__inner">
      <!-- 第 0 行：内容三态（固定值 / 变量 / 表达式），与文本组件完全一致 -->
      <div class="op-cell-toolbar__row">
        <span class="op-cell-toolbar__tag">内容</span>
        <ContentValueEditor
          class="op-cell-content"
          compact
          :mode="cellMode"
          :value="cell.text ?? ''"
          :binding="cell.field ?? ''"
          :expression="cell.expression ?? ''"
          placeholder="单元格内容"
          :binding-default="bindingDefault"
          :expression-default="expressionDefault"
          @update:mode="onCellMode"
          @update:value="onCellValue"
          @update:binding="onCellBinding"
          @update:expression="onCellExpression"
        />
      </div>

      <!-- 第一行：行角色 / 字体 / 字形 / 对齐 -->
      <div class="op-cell-toolbar__row">
        <span class="op-cell-toolbar__tag">{{ roleLabel }}</span>

        <NDivider vertical />

        <NSelect
          size="tiny"
          class="w-24"
          :value="style.fontFamily ?? ''"
          :options="fontOptions"
          filterable
          @update:value="(v: string) => applyStyle({ fontFamily: v || undefined })"
        />
        <NInputNumber
          size="tiny"
          class="w-18"
          button-placement="both"
          :value="style.fontSize ?? null"
          :min="5"
          :max="72"
          :step="1"
          placeholder="9"
          @update:value="(v: number | null) => applyStyle({ fontSize: v ?? undefined })"
        />

        <NButtonGroup size="tiny">
          <NTooltip trigger="hover">
            <template #trigger>
              <NButton :type="style.bold ? 'primary' : 'default'" @click="toggle('bold')">
                <span class="font-bold">B</span>
              </NButton>
            </template>
            加粗
          </NTooltip>
          <NTooltip trigger="hover">
            <template #trigger>
              <NButton :type="style.italic ? 'primary' : 'default'" @click="toggle('italic')">
                <span class="italic font-serif">I</span>
              </NButton>
            </template>
            斜体
          </NTooltip>
          <NTooltip trigger="hover">
            <template #trigger>
              <NButton :type="style.underline ? 'primary' : 'default'" @click="toggle('underline')">
                <span class="underline">U</span>
              </NButton>
            </template>
            下划线
          </NTooltip>
        </NButtonGroup>

        <NButtonGroup size="tiny">
          <NTooltip
            v-for="a in (['left', 'center', 'right'] as const)"
            :key="a"
            trigger="hover"
          >
            <template #trigger>
              <NButton
                :type="style.align === a ? 'primary' : 'default'"
                @click="applyStyle({ align: a })"
              >
                <span :class="`i-carbon-text-align-${a}`" />
              </NButton>
            </template>
            {{ { left: '左对齐', center: '居中', right: '右对齐' }[a] }}
          </NTooltip>
        </NButtonGroup>

        <NButtonGroup size="tiny">
          <NTooltip
            v-for="v in (['top', 'middle', 'bottom'] as const)"
            :key="v"
            trigger="hover"
          >
            <template #trigger>
              <NButton
                :type="style.valign === v ? 'primary' : 'default'"
                @click="applyStyle({ valign: v })"
              >
                <span :class="`i-carbon-align-vertical-${v === 'middle' ? 'center' : v}`" />
              </NButton>
            </template>
            {{ { top: '顶端对齐', middle: '垂直居中', bottom: '底端对齐' }[v] }}
          </NTooltip>
        </NButtonGroup>
      </div>

      <!-- 第二行：文字色 / 填充色 / 合并 / 清除 -->
      <div class="op-cell-toolbar__row">
        <!-- 文字颜色：自定义触发器 + to=false 让面板留在工具栏内，避免点选时工具栏被收起 -->
        <NColorPicker
          :value="isColorExpr ? '#1f2329' : (style.color ?? '#1f2329')"
          :show-alpha="false"
          :modes="['hex']"
          :to="false"
          size="small"
          @update:value="(v: string) => applyStyle({ color: v || undefined })"
        >
          <template #trigger="{ value, onClick, ref: triggerRef }">
            <NButton :ref="triggerRef" size="tiny" quaternary title="文字颜色" @click="onClick">
              <span class="i-carbon-text-color" />
              <span v-if="isColorExpr" class="op-cell-toolbar__swatch op-cell-toolbar__swatch--fx" title="表达式配色">
                <span class="i-carbon-function" />
              </span>
              <span v-else class="op-cell-toolbar__swatch" :style="{ background: value || '#1f2329' }" />
            </NButton>
          </template>
        </NColorPicker>
        <!-- 文字色：切到表达式模式（fx 按钮） -->
        <NButton size="tiny" quaternary title="文字色表达式（如 {{row.amount < 0 ? '#D93636' : ''}}）" @click="colorExprShow = true">
          <span class="i-carbon-function" :class="{ 'is-active': isColorExpr }" />
        </NButton>

        <!-- 填充颜色（含清除） -->
        <NColorPicker
          :value="isBgExpr ? '#ffffff' : (style.backgroundColor ?? '#ffffff')"
          :show-alpha="false"
          :modes="['hex']"
          :to="false"
          size="small"
          @update:value="(v: string) => applyStyle({ backgroundColor: v || undefined })"
        >
          <template #trigger="{ value, onClick, ref: triggerRef }">
            <NButton :ref="triggerRef" size="tiny" quaternary title="填充颜色" @click="onClick">
              <span class="i-carbon-paint-brush" />
              <span v-if="isBgExpr" class="op-cell-toolbar__swatch op-cell-toolbar__swatch--fx" title="表达式配色">
                <span class="i-carbon-function" />
              </span>
              <span
                v-else
                class="op-cell-toolbar__swatch"
                :style="{ background: value || 'transparent' }"
              />
            </NButton>
          </template>
        </NColorPicker>
        <!-- 填充色：切到表达式模式（fx 按钮） -->
        <NButton size="tiny" quaternary title="填充色表达式（如 {{row.amount < 0 ? '#FFE5E5' : '#fff'}}）" @click="bgExprShow = true">
          <span class="i-carbon-function" :class="{ 'is-active': isBgExpr }" />
        </NButton>
        <NButton size="tiny" quaternary title="清除填充" @click="applyStyle({ backgroundColor: undefined })">
          <span class="i-carbon-clean" />
        </NButton>

        <NTooltip trigger="hover">
          <template #trigger>
            <NSelect
              size="tiny"
              style="width: 92px"
              :value="currentDiagonal"
              :options="diagOptions"
              @update:value="setDiagonal"
            />
          </template>
          单元格斜线（课表角标）：无 / ↘左上→右下 / ↗左下→右上
        </NTooltip>

        <NDivider vertical />

        <NTooltip trigger="hover">
          <template #trigger>
            <NInputNumber
              size="tiny"
              class="w-20"
              button-placement="both"
              :value="currentSpan"
              :min="1"
              :max="spanMax"
              :step="1"
              @update:value="setSpan"
            />
          </template>
          横向合并列数
        </NTooltip>

        <NTooltip trigger="hover">
          <template #trigger>
            <NInputNumber
              size="tiny"
              class="w-20"
              :value="currentRowSpan"
              button-placement="both"
              :min="1"
              :max="rowSpanMax"
              :step="1"
              :disabled="!canRowSpan"
              @update:value="setRowSpan"
            />
          </template>
          纵向合并行数（数据行不跨行）
        </NTooltip>

        <NDivider vertical />

        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary @click="clearStyle">
              <span class="i-carbon-clean" />
            </NButton>
          </template>
          清除本格样式
        </NTooltip>

        <NDivider vertical />

        <span class="op-cell-toolbar__tag">行列</span>
        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary title="上方插入行" @click="insertRowAbove">
              <span class="i-carbon-arrow-up" />
            </NButton>
          </template>
          上方插入行
        </NTooltip>
        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary title="下方插入行" @click="insertRowBelow">
              <span class="i-carbon-arrow-down" />
            </NButton>
          </template>
          下方插入行
        </NTooltip>
        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary title="左侧插入列" @click="insertColLeft">
              <span class="i-carbon-arrow-left" />
            </NButton>
          </template>
          左侧插入列
        </NTooltip>
        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary title="右侧插入列" @click="insertColRight">
              <span class="i-carbon-arrow-right" />
            </NButton>
          </template>
          右侧插入列
        </NTooltip>

        <NDivider vertical />

        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary :disabled="!canDeleteRow" title="删除本行" @click="deleteRow">
              <span class="i-carbon-trash-can" />
            </NButton>
          </template>
          删除本行
        </NTooltip>
        <NTooltip trigger="hover">
          <template #trigger>
            <NButton size="tiny" quaternary :disabled="!canDeleteCol" title="删除本列" @click="deleteCol">
              <span class="i-carbon-trash-can" />
            </NButton>
          </template>
          删除本列
        </NTooltip>

        <NButton size="tiny" quaternary @click="emit('close')">
          <span class="i-carbon-close" />
        </NButton>
      </div>

      <!-- 第三行：数据格式（仅绑定字段的单元格） -->
      <div v-if="canFormat" class="op-cell-toolbar__row op-cell-toolbar__format">
        <span class="op-cell-toolbar__tag">格式</span>
        <NSelect
          size="tiny"
          class="w-24"
          :value="cellFormat?.kind ?? 'none'"
          :options="formatKindOptions"
          @update:value="(k: CellFormatKind) => applyFormat(k === 'none' ? undefined : makeFormat(k))"
        />
        <template v-if="cellFormat && cellFormat.kind !== 'none'">
          <NSelect
            v-if="needsPattern(cellFormat.kind)"
            size="tiny"
            class="w-30"
            :value="isPresetDatePattern(cellFormat.pattern) ? cellFormat.pattern : '__custom__'"
            :options="datePatternOptions"
            @update:value="(v: string) => { if (v !== '__custom__') applyFormat({ ...cellFormat!, pattern: v }) }"
          />
          <NInput
            v-if="needsPattern(cellFormat.kind) && !isPresetDatePattern(cellFormat.pattern)"
            size="tiny"
            class="w-30"
            :value="cellFormat.pattern"
            placeholder="如 YYYY年MM月DD日"
            @update:value="(v: string) => applyFormat({ ...cellFormat!, pattern: v || 'YYYY-MM-DD' })"
          />
          <NInputNumber
            v-if="needsDigits(cellFormat.kind)"
            size="tiny"
            class="w-16"
            button-placement="both"
            :value="cellFormat.digits ?? (cellFormat.kind === 'int' ? 0 : 2)"
            :min="0"
            :max="6"
            @update:value="(v: number | null) => applyFormat({ ...cellFormat!, digits: v ?? 0 })"
          />
          <NSelect
            v-if="needsCode(cellFormat.kind)"
            size="tiny"
            class="w-20"
            :value="cellFormat.code ?? 'CNY'"
            :options="currencyCodeOptions"
            @update:value="(v: string) => applyFormat({ ...cellFormat!, code: v })"
          />
          <NSwitch
            v-if="supportsThousands(cellFormat.kind)"
            size="small"
            :value="cellFormat.thousands ?? true"
            @update:value="(v: boolean) => applyFormat({ ...cellFormat!, thousands: v })"
          />
        </template>
      </div>
    </div>

    <!-- 动态配色：文字色 / 填充色表达式编辑 -->
    <ExpressionModal
      v-model:show="colorExprShow"
      :expression="colorExprInit"
      @confirm="onColorExprConfirm"
    />
    <ExpressionModal
      v-model:show="bgExprShow"
      :expression="bgExprInit"
      @confirm="onBgExprConfirm"
    />
  </div>
</template>

<style scoped>
.op-cell-toolbar {
  position: absolute;
  transform: translateY(-100%) translateY(-8px);
  pointer-events: auto;
  z-index: 30;
}

.op-cell-toolbar__inner {
  display: flex;
  flex-direction: column;
  gap: 4px;
  padding: 4px 6px;
  border-radius: 6px;
  background: var(--brand-surface, #ffffff);
  border: 1px solid var(--brand-border, #e5e6eb);
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.12);
  max-width: 92vw;
}

.op-cell-toolbar__row {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 4px;
}

.op-cell-toolbar__tag {
  font-size: 11px;
  color: var(--brand-text-secondary, #86909c);
  padding-right: 2px;
}

.op-cell-toolbar__swatch {
  display: inline-block;
  width: 12px;
  height: 12px;
  border-radius: 2px;
  border: 1px solid rgba(0, 0, 0, 0.15);
  vertical-align: middle;
}
/* 表达式配色时，色块占位显示 fx 图标 + 紫底，提示此处由表达式求值 */
.op-cell-toolbar__swatch--fx {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #b084ff 0%, #6b5cff 100%);
  border-color: rgba(107, 92, 255, 0.5);
  color: #fff;
}
.op-cell-toolbar__swatch--fx .i-carbon-function {
  font-size: 10px;
  line-height: 1;
}
/* fx 按钮处于激活态（值已是表达式）时高亮 */
.i-carbon-function.is-active {
  color: #6b5cff;
}
</style>

// designer-react/src/canvas/CellToolbar.tsx
/**
 * CellToolbar —— 单元格浮动工具栏（React 版，方案 A）
 *
 * 从 Vue 版 `openprint/src/design/canvas/CellToolbar.vue` 迁移（P7 收尾）。
 * 双击进入单元格后浮在其上方，提供 ERP 报表最常用的单元格级能力：
 * 字段绑定 / 字体族 / 字号 / 加粗斜体下划线 / 水平垂直对齐 / 文字色 / 填充色 /
 * 横纵向合并 / 单元格斜线 / 行列增删 / 数据格式 / 清除样式。
 *
 * 交互契约（与 Vue 版逐条对齐）：
 * - 本组件**不直接改 store**：所有动作算出「新的表格控件」后 onApply(next)，
 *   由 TableViewLayer 统一写回并重放冻结 HTML —— 保持单一写入口，撤销栈干净。
 * - 浮层内的 mousedown / dblclick 一律 stopPropagation，避免按钮点击被画布的
 *   「点外面就退出编辑」逻辑吞掉，也避免触发 Fabric 的命中。
 *
 * antd v6 适配要点（与 Vue/naive 的差异）：
 * - naive `<NButtonGroup>` → `Space.Compact`；`NSelect/NInputNumber/NSwitch` → 同名 antd 组件
 * - `NColorPicker value+@update:value` → antd `ColorPicker`（`children` 自定义触发器 + `onChange(c, css)`）
 * - React 端 UnoCSS **无 presetIcons**（无 `i-carbon-*`），图标统一用 Unicode 字符 + 文字
 * - 两字中文按钮会被 antd 插入空格 → 统一 `autoInsertSpace={false}`
 * - 下拉/取色器弹层走 body 传送门，由 TableViewLayer 的 ANTD_TELEPORT_SELECTOR 豁免
 */
import { useMemo, useState } from 'react'
import type { ReactNode } from 'react'
import { Button, ColorPicker, Divider, Input, InputNumber, Select, Space, Switch, Tooltip } from 'antd'
import type {
  CellFormat,
  CellFormatKind,
  TableCell,
  TableCellStyle,
  TableControl,
} from '@/types/control'
import {
  buildDesignGrid,
  insertTableColumn,
  insertTableRow,
  patchCell,
  patchCellStyle,
  removeTableColumn,
  removeTableRow,
  resolveCellStyle,
  rowRoleLabel,
  setCellRowSpan,
  setCellSpan,
} from '@/core/layout-engine/table-cells'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '../hooks/useSystemFonts'
import { selectActiveSource, selectFlatFields, useDataSourceStore } from '../stores/dataSource'
import ContentValueEditor from '../panels/props/ContentValueEditor'
import type { ContentMode } from '../panels/props/ContentValueEditor'
import ExpressionModal from '../panels/props/ExpressionModal'
import {
  currencyCodeOptions,
  datePatternOptions,
  formatKindOptions,
  makeFormat,
  needsCode,
  needsDigits,
  needsPattern,
  supportsThousands,
} from '@/design/format-options'

export interface CellToolbarProps {
  control: TableControl
  row: number
  col: number
  /** 行语义：header=表头 / data=数据样例行（影响整列）/ static=静态行 */
  rowKind: 'header' | 'data' | 'static'
  x: number
  y: number
  onApply: (next: TableControl) => void
  onClose: () => void
}

/** antd ColorPicker 的 onChange 第二参（css 串）在不同格式下形态不一，统一取 6 位 hex */
function toHex6(c: { toHexString: () => string } | null | undefined): string {
  if (!c || typeof c.toHexString !== 'function') return ''
  try {
    const h = c.toHexString()
    return h.length === 9 ? h.slice(0, 7) : h
  } catch {
    return ''
  }
}

/** 自定义触发器按钮（取色器用），带色块 / fx 占位 */
function SwatchTrigger({ value, children }: { value?: string; children: ReactNode }): ReactNode {
  return (
    <span className="op-cell-toolbar__swatch-trigger">
      {children}
      <span className="op-cell-toolbar__swatch" style={{ background: value || 'transparent' }} />
    </span>
  )
}

export default function CellToolbar(props: CellToolbarProps) {
  const { control, row, col, rowKind, x, y, onApply, onClose } = props

  const flatFields = useDataSourceStore(selectFlatFields)
  const activeSource = useDataSourceStore(selectActiveSource)
  const sysFonts = useSystemFonts()

  const [colorExprShow, setColorExprShow] = useState(false)
  const [bgExprShow, setBgExprShow] = useState(false)

  const grid = useMemo(() => buildDesignGrid(control), [control])
  const cell: TableCell = grid.cells[row]?.[col] ?? {}
  const column = control.columns[col]
  const style: TableCellStyle = resolveCellStyle(control, column, cell)

  /* ------------------------------ 字体下拉 ------------------------------ */

  type FontOption = { label: string; value: string }
  type FontGroup = { label: string; options: FontOption[] }

  const fontOptions = useMemo<Array<FontOption | FontGroup>>(() => {
    const out: Array<FontOption | FontGroup> = [{ label: '默认', value: '' }]
    if (sysFonts.ready) {
      out.push({
        label: '预设字体',
        options: FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })),
      })
      out.push({
        label: `电脑系统字体（${sysFonts.count}）`,
        options: sysFonts.grouped.map((g) => ({ label: g.family, value: g.family })),
      })
    } else {
      out.push(...FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })))
    }
    return out
  }, [sysFonts])

  /* ------------------------------ 字段绑定 ------------------------------ */

  /**
   * 可绑定字段（用于变量模式默认值）：
   * - 数据样例行 → 明细表（数组）字段，运行期按行迭代
   * - 表头 / 静态行 → 主表标量字段
   */
  const detailFields = useMemo(() => {
    const isDetail = rowKind === 'data'
    const tables = activeSource?.tables ?? []
    const arrayTableIds = new Set(tables.filter((t) => t.isArray).map((t) => t.id))
    return flatFields.filter((f) => {
      const inArray = f.tableId ? arrayTableIds.has(f.tableId) : f.path.includes('[]')
      return isDetail ? inArray : !inArray
    })
  }, [flatFields, activeSource, rowKind])

  const bindingDefault =
    detailFields[0]?.path ?? (rowKind === 'data' ? 'items[].name' : 'order.orderNo')
  const expressionDefault = rowKind === 'data' ? '{{rowIndex + 1}}' : '{{order.total}}'

  /** 单元格内容三态：固定值 / 变量（字段绑定） / 表达式（显式 contentType，老模板启发式回退） */
  const cellMode: ContentMode = cell.contentType
    ? cell.contentType
    : cell.expression
      ? 'expression'
      : cell.field
        ? 'variable'
        : 'fixed'

  /** 模式切换：写 contentType + 清空其它两个字段（默认值由编辑器按 bindingDefault 注入） */
  function onCellMode(m: ContentMode): void {
    const p: Partial<TableCell> = { contentType: m }
    if (m === 'fixed') {
      p.field = undefined
      p.expression = undefined
    } else if (m === 'variable') {
      p.expression = undefined
    } else {
      p.field = undefined
    }
    onApply(patchCell(control, row, col, p))
  }

  function onCellValue(v: string): void {
    onApply(patchCell(control, row, col, { text: v }))
  }

  /** 变量模式：写 contentType + field 并清空 text/expression，保证 field 为唯一取值源 */
  function onCellBinding(path: string): void {
    onApply(
      patchCell(control, row, col, {
        contentType: 'variable',
        field: path || undefined,
        text: undefined,
        expression: undefined,
      }),
    )
  }

  function onCellExpression(v: string): void {
    onApply(
      patchCell(control, row, col, {
        contentType: 'expression',
        expression: v || undefined,
        text: undefined,
        field: undefined,
      }),
    )
  }

  /* ------------------------------ 样式动作 ------------------------------ */

  function applyStyle(patch: TableCellStyle): void {
    onApply(patchCellStyle(control, row, col, patch))
  }

  /* ----- 动态配色：把 {{}} 表达式写入列级 columns[i].style ----- */

  const colorExprInit = column?.style?.color ?? ''
  const bgExprInit = column?.style?.backgroundColor ?? ''

  /** 文字色 / 填充色是否处于「表达式模式」（值含 {{）—— 此时色块按钮显示 fx 占位 */
  const isColorExpr = /\{\{/.test(column?.style?.color ?? '')
  const isBgExpr = /\{\{/.test(column?.style?.backgroundColor ?? '')

  /** 写入列级 style（columns[i].style），整列数据行生效 */
  function applyColumnStyle(patch: TableCellStyle): void {
    const cur = column?.style ?? {}
    const merged: TableCellStyle = { ...cur }
    for (const [k, v] of Object.entries(patch)) {
      if (v === undefined) delete (merged as Record<string, unknown>)[k]
      else (merged as Record<string, unknown>)[k] = v
    }
    const columns = control.columns.map((c, i) => (i === col ? { ...c, style: merged } : c))
    onApply({ ...control, columns })
  }

  function toggle(key: 'bold' | 'italic' | 'underline'): void {
    applyStyle({ [key]: !style[key] } as TableCellStyle)
  }

  /* ------------------------------ 合并 ------------------------------ */

  const spanMax = Math.max(1, grid.colCount - col)
  const currentSpan = Math.min(cell.colSpan ?? 1, spanMax)

  function setSpan(n: number | null): void {
    onApply(setCellSpan(control, row, col, n ?? 1))
  }

  /**
   * 纵向合并（rowSpan）。
   * 仅表头 / 静态 / 布局网格行生效：数据行由运行期逐条生成，跨行会跨越不同记录，语义不成立，
   * 故数据样例行（rowKind==='data'）禁用该项，与表格引擎的「模板行强制 rowSpan=1」一致。
   */
  const canRowSpan = rowKind !== 'data'
  const rowSpanMax = Math.max(1, grid.rowCount - row)
  const currentRowSpan = Math.min(cell.rowSpan ?? 1, rowSpanMax)

  function setRowSpanValue(n: number | null): void {
    if (!canRowSpan) return
    onApply(setCellRowSpan(control, row, col, n ?? 1))
  }

  function clearStyle(): void {
    onApply(patchCell(control, row, col, { style: undefined }))
  }

  /* ------------------------------ 斜线 ------------------------------ */

  const diagOptions = [
    { label: '无', value: 'none' },
    { label: '↘ 右下', value: 'down' },
    { label: '↗ 右上', value: 'up' },
  ]
  const currentDiagonal = (cell.style?.diagonal ?? 'none') as 'none' | 'down' | 'up'
  function setDiagonal(v: 'none' | 'down' | 'up'): void {
    applyStyle({ diagonal: v === 'none' ? undefined : v })
  }

  /* ------------------------------ 数据格式 ------------------------------ */

  /** 仅绑定了字段/表达式（或显式 variable/expression 模式）的单元格才需要格式 */
  const canFormat =
    cell.contentType === 'variable' ||
    cell.contentType === 'expression' ||
    Boolean(cell.field || cell.expression) ||
    (rowKind === 'data' && Boolean(column?.field || column?.expression))

  /** 生效中的格式（单元格优先，回落列默认） */
  const cellFormat: CellFormat | undefined = cell.format ?? column?.format

  function applyFormat(fmt: CellFormat | undefined): void {
    // kind='none' 视为清除，避免脏字段
    onApply(
      patchCell(control, row, col, { format: fmt && fmt.kind !== 'none' ? fmt : undefined }),
    )
  }

  function isPresetDatePattern(p?: string): boolean {
    return Boolean(p && datePatternOptions.some((o) => o.value !== '__custom__' && o.value === p))
  }

  /* ------------------------------ 行列插入/删除 ------------------------------ */

  const canDeleteRow = rowKind !== 'data' && grid.rowCount > 1
  const canDeleteCol = grid.colCount > 1

  /* ------------------------------ 行角色名 ------------------------------ */

  /** 行角色名（标题行 / 数据行 / 本页合计行 / 总计行 / 大写金额行），用于工具栏标签 */
  const roleLabel = rowKind === 'data' ? '数据行（影响整列）' : rowRoleLabel(grid, row)

  const alignOptions = [
    { key: 'left', icon: '⇤', title: '左对齐' },
    { key: 'center', icon: '↔', title: '居中' },
    { key: 'right', icon: '⇥', title: '右对齐' },
  ] as const
  const valignOptions = [
    { key: 'top', icon: '⇡', title: '顶端对齐' },
    { key: 'middle', icon: '⇕', title: '垂直居中' },
    { key: 'bottom', icon: '⇣', title: '底端对齐' },
  ] as const

  const smallBtn = { size: 'small' as const, autoInsertSpace: false }

  return (
    <div
      className="op-cell-toolbar"
      style={{ left: x, top: y }}
      data-testid="cell-toolbar"
      onMouseDown={(e) => e.stopPropagation()}
      onDoubleClick={(e) => e.stopPropagation()}
    >
      <div className="op-cell-toolbar__inner">
        {/* 第 0 行：内容三态（固定值 / 变量 / 表达式），与文本组件完全一致 */}
        <div className="op-cell-toolbar__row">
          <span className="op-cell-toolbar__tag">内容</span>
          <div className="op-cell-content">
            <ContentValueEditor
              mode={cellMode}
              value={cell.text ?? ''}
              binding={cell.field ?? ''}
              expression={cell.expression ?? ''}
              placeholder="单元格内容"
              singleLine
              bindingDefault={bindingDefault}
              expressionDefault={expressionDefault}
              onModeChange={onCellMode}
              onValueChange={onCellValue}
              onBindingChange={onCellBinding}
              onExpressionChange={onCellExpression}
            />
          </div>
        </div>

        {/* 第一行：行角色 / 字体 / 字形 / 对齐 */}
        <div className="op-cell-toolbar__row">
          <span className="op-cell-toolbar__tag" data-testid="cell-role">{roleLabel}</span>

          <Divider orientation="vertical" />

          <Select
            size="small"
            className="op-cell-toolbar__w24"
            value={style.fontFamily ?? ''}
            options={fontOptions}
            showSearch
            optionFilterProp="label"
            data-testid="cell-font"
            onChange={(v: string) => applyStyle({ fontFamily: v || undefined })}
          />
          <InputNumber
            size="small"
            className="op-cell-toolbar__w18"
            value={style.fontSize ?? null}
            min={5}
            max={72}
            step={1}
            placeholder="9"
            onChange={(v: number | null) => applyStyle({ fontSize: v ?? undefined })}
          />

          <Space.Compact>
            <Tooltip title="加粗">
              <Button
                {...smallBtn}
                data-testid="cell-bold"
                type={style.bold ? 'primary' : 'default'}
                onClick={() => toggle('bold')}
              >
                <span className="font-bold">B</span>
              </Button>
            </Tooltip>
            <Tooltip title="斜体">
              <Button
                {...smallBtn}
                data-testid="cell-italic"
                type={style.italic ? 'primary' : 'default'}
                onClick={() => toggle('italic')}
              >
                <span className="italic font-serif">I</span>
              </Button>
            </Tooltip>
            <Tooltip title="下划线">
              <Button
                {...smallBtn}
                data-testid="cell-underline"
                type={style.underline ? 'primary' : 'default'}
                onClick={() => toggle('underline')}
              >
                <span className="underline">U</span>
              </Button>
            </Tooltip>
          </Space.Compact>

          <Space.Compact>
            {alignOptions.map((a) => (
              <Tooltip key={a.key} title={a.title}>
                <Button
                  {...smallBtn}
                  type={style.align === a.key ? 'primary' : 'default'}
                  onClick={() => applyStyle({ align: a.key })}
                >
                  <span className="op-cell-toolbar__icon">{a.icon}</span>
                </Button>
              </Tooltip>
            ))}
          </Space.Compact>

          <Space.Compact>
            {valignOptions.map((v) => (
              <Tooltip key={v.key} title={v.title}>
                <Button
                  {...smallBtn}
                  type={style.valign === v.key ? 'primary' : 'default'}
                  onClick={() => applyStyle({ valign: v.key })}
                >
                  <span className="op-cell-toolbar__icon">{v.icon}</span>
                </Button>
              </Tooltip>
            ))}
          </Space.Compact>
        </div>

        {/* 第二行：文字色 / 填充色 / 斜线 / 合并 / 清除 / 行列 */}
        <div className="op-cell-toolbar__row">
          {/* 文字颜色：自定义触发器，色块展示当前值；表达式模式下显示 fx */}
          <ColorPicker
            value={isColorExpr ? '#1f2329' : (style.color ?? '#1f2329')}
            disabledAlpha
            format="hex"
            size="small"
            onChange={(c) => applyStyle({ color: toHex6(c) || undefined })}
          >
            <Button {...smallBtn} type="text" title="文字颜色" data-testid="cell-color">
              <SwatchTrigger value={isColorExpr ? undefined : (style.color ?? '#1f2329')}>
                {isColorExpr ? (
                  <span className="i-fx">fx</span>
                ) : (
                  <span className="font-bold">A</span>
                )}
              </SwatchTrigger>
            </Button>
          </ColorPicker>
          {/* 文字色：切到表达式模式（fx 按钮） */}
          <Tooltip title="文字色表达式（如 {{row.amount < 0 ? '#D93636' : ''}}）">
            <Button
              {...smallBtn}
              type={isColorExpr ? 'primary' : 'text'}
              data-testid="cell-color-expr"
              onClick={() => setColorExprShow(true)}
            >
              fx
            </Button>
          </Tooltip>

          {/* 填充颜色 */}
          <ColorPicker
            value={isBgExpr ? '#ffffff' : (style.backgroundColor ?? '#ffffff')}
            disabledAlpha
            format="hex"
            size="small"
            onChange={(c) => applyStyle({ backgroundColor: toHex6(c) || undefined })}
          >
            <Button {...smallBtn} type="text" title="填充颜色" data-testid="cell-bg">
              <SwatchTrigger value={isBgExpr ? undefined : style.backgroundColor}>
                {isBgExpr ? <span className="i-fx">fx</span> : <span>▨</span>}
              </SwatchTrigger>
            </Button>
          </ColorPicker>
          {/* 填充色：切到表达式模式（fx 按钮） */}
          <Tooltip title="填充色表达式（如 {{row.amount < 0 ? '#FFE5E5' : '#fff'}}）">
            <Button
              {...smallBtn}
              type={isBgExpr ? 'primary' : 'text'}
              data-testid="cell-bg-expr"
              onClick={() => setBgExprShow(true)}
            >
              fx
            </Button>
          </Tooltip>
          <Tooltip title="清除填充">
            <Button
              {...smallBtn}
              type="text"
              onClick={() => applyStyle({ backgroundColor: undefined })}
            >
              ⌫
            </Button>
          </Tooltip>

          <Tooltip title="单元格斜线（课表角标）：无 / ↘左上→右下 / ↗左下→右上">
            <Select
              size="small"
              style={{ width: 92 }}
              value={currentDiagonal}
              options={diagOptions}
              data-testid="cell-diagonal"
              onChange={(v: 'none' | 'down' | 'up') => setDiagonal(v)}
            />
          </Tooltip>

          <Divider orientation="vertical" />

          <Tooltip title="横向合并列数">
            <InputNumber
              size="small"
              className="op-cell-toolbar__w20"
              value={currentSpan}
              min={1}
              max={spanMax}
              step={1}
              data-testid="cell-span"
              onChange={setSpan}
            />
          </Tooltip>
          <Tooltip title="纵向合并行数（数据行不跨行）">
            <InputNumber
              size="small"
              className="op-cell-toolbar__w20"
              value={currentRowSpan}
              min={1}
              max={rowSpanMax}
              step={1}
              disabled={!canRowSpan}
              data-testid="cell-rowspan"
              onChange={setRowSpanValue}
            />
          </Tooltip>

          <Divider orientation="vertical" />

          <Tooltip title="清除本格样式">
            <Button {...smallBtn} type="text" onClick={clearStyle}>
              ⌫
            </Button>
          </Tooltip>

          <Divider orientation="vertical" />

          <span className="op-cell-toolbar__tag">行列</span>
          <Tooltip title="上方插入行">
            <Button
              {...smallBtn}
              type="text"
              data-testid="cell-insert-row-above"
              onClick={() => onApply(insertTableRow(control, row))}
            >
              ↑行
            </Button>
          </Tooltip>
          <Tooltip title="下方插入行">
            <Button
              {...smallBtn}
              type="text"
              data-testid="cell-insert-row-below"
              onClick={() => onApply(insertTableRow(control, row + 1))}
            >
              ↓行
            </Button>
          </Tooltip>
          <Tooltip title="左侧插入列">
            <Button
              {...smallBtn}
              type="text"
              data-testid="cell-insert-col-left"
              onClick={() => onApply(insertTableColumn(control, col))}
            >
              ←列
            </Button>
          </Tooltip>
          <Tooltip title="右侧插入列">
            <Button
              {...smallBtn}
              type="text"
              data-testid="cell-insert-col-right"
              onClick={() => onApply(insertTableColumn(control, col + 1))}
            >
              →列
            </Button>
          </Tooltip>

          <Divider orientation="vertical" />

          <Tooltip title="删除本行">
            <Button
              {...smallBtn}
              type="text"
              disabled={!canDeleteRow}
              data-testid="cell-del-row"
              onClick={() => onApply(removeTableRow(control, row))}
            >
              ✕行
            </Button>
          </Tooltip>
          <Tooltip title="删除本列">
            <Button
              {...smallBtn}
              type="text"
              disabled={!canDeleteCol}
              data-testid="cell-del-col"
              onClick={() => onApply(removeTableColumn(control, col))}
            >
              ✕列
            </Button>
          </Tooltip>

          <Button {...smallBtn} type="text" data-testid="cell-close" onClick={onClose}>
            ✕
          </Button>
        </div>

        {/* 第三行：数据格式（仅绑定字段的单元格） */}
        {canFormat && (
          <div className="op-cell-toolbar__row op-cell-toolbar__format">
            <span className="op-cell-toolbar__tag">格式</span>
            <Select
              size="small"
              className="op-cell-toolbar__w24"
              value={cellFormat?.kind ?? 'none'}
              options={formatKindOptions}
              data-testid="cell-format-kind"
              onChange={(k: CellFormatKind) => applyFormat(k === 'none' ? undefined : makeFormat(k))}
            />
            {cellFormat && cellFormat.kind !== 'none' && (
              <>
                {needsPattern(cellFormat.kind) && (
                  <Select
                    size="small"
                    className="op-cell-toolbar__w30"
                    value={
                      isPresetDatePattern(cellFormat.pattern)
                        ? cellFormat.pattern
                        : '__custom__'
                    }
                    options={datePatternOptions}
                    onChange={(v: string) => {
                      if (v !== '__custom__') applyFormat({ ...cellFormat, pattern: v })
                    }}
                  />
                )}
                {needsPattern(cellFormat.kind) && !isPresetDatePattern(cellFormat.pattern) && (
                  <Input
                    size="small"
                    className="op-cell-toolbar__w30"
                    value={cellFormat.pattern}
                    placeholder="如 YYYY年MM月DD日"
                    onChange={(e) =>
                      applyFormat({ ...cellFormat, pattern: e.target.value || 'YYYY-MM-DD' })
                    }
                  />
                )}
                {needsDigits(cellFormat.kind) && (
                  <InputNumber
                    size="small"
                    className="op-cell-toolbar__w16"
                    value={cellFormat.digits ?? (cellFormat.kind === 'int' ? 0 : 2)}
                    min={0}
                    max={6}
                    onChange={(v: number | null) => applyFormat({ ...cellFormat, digits: v ?? 0 })}
                  />
                )}
                {needsCode(cellFormat.kind) && (
                  <Select
                    size="small"
                    className="op-cell-toolbar__w20"
                    value={cellFormat.code ?? 'CNY'}
                    options={currencyCodeOptions}
                    onChange={(v: string) => applyFormat({ ...cellFormat, code: v })}
                  />
                )}
                {supportsThousands(cellFormat.kind) && (
                  <Switch
                    size="small"
                    checked={cellFormat.thousands ?? true}
                    onChange={(v: boolean) => applyFormat({ ...cellFormat, thousands: v })}
                  />
                )}
              </>
            )}
          </div>
        )}
      </div>

      {/* 动态配色：文字色 / 填充色表达式编辑 */}
      <ExpressionModal
        show={colorExprShow}
        expression={colorExprInit}
        onCancel={() => setColorExprShow(false)}
        onConfirm={(v) => {
          applyColumnStyle({ color: v || undefined })
          setColorExprShow(false)
        }}
      />
      <ExpressionModal
        show={bgExprShow}
        expression={bgExprInit}
        onCancel={() => setBgExprShow(false)}
        onConfirm={(v) => {
          applyColumnStyle({ backgroundColor: v || undefined })
          setBgExprShow(false)
        }}
      />
    </div>
  )
}
