// openprint/src/design/panels/props/RichTextEditor.vue
<script setup lang="ts">
/**
 * RichTextEditor —— 富文本编辑器（tiptap v3 + StarterKit + 字体扩展，懒加载）
 * 由 RichTextProps 通过 defineAsyncComponent 引入，未选中富文本时不加载 tiptap。
 */
import { onBeforeUnmount, ref, computed, watch } from 'vue'
import { NButton, NSelect } from 'naive-ui'
import type { SelectOption, SelectGroupOption } from 'naive-ui'
import { Editor, EditorContent } from '@tiptap/vue-3'
import StarterKit from '@tiptap/starter-kit'
import { TextStyle } from '@tiptap/extension-text-style'
import { FontFamily } from '@tiptap/extension-font-family'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '@/design/composables/useSystemFonts'

const props = defineProps<{ modelValue?: string }>()
const emit = defineEmits<{ (e: 'update:modelValue', v: string): void }>()

const editor = new Editor({
  extensions: [StarterKit, TextStyle, FontFamily],
  content: props.modelValue ?? '',
  onUpdate: ({ editor }) => emit('update:modelValue', editor.getHTML()),
})

/** 外部改动（撤销/加载模板/重置）→ 回写编辑器；emitUpdate:false 避免触发 onUpdate 死循环 */
watch(
  () => props.modelValue,
  (v) => {
    if (editor && v !== editor.getHTML()) {
      editor.commands.setContent(v ?? '', { emitUpdate: false })
    }
  },
)

onBeforeUnmount(() => {
  editor.destroy()
})

/* ------------------------------ 字体选择 ------------------------------ */

/** 编辑器当前字体族（textStyle mark 上） */
const currentFont = ref('')
const refreshFont = (): void => {
  currentFont.value = (editor.getAttributes('textStyle').fontFamily as string | undefined) ?? ''
}
editor.on('selectionUpdate', refreshFont)
editor.on('transaction', refreshFont)
watch(
  () => props.modelValue,
  () => refreshFont(),
)

const sysFonts = useSystemFonts()

const FONT_OPTIONS = computed<(SelectOption | SelectGroupOption)[]>(() => {
  const builtin: SelectOption[] = [
    { label: '系统默认', value: '' },
    ...FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })),
  ]
  if (!sysFonts.ready.value) return builtin
  const sysOpts: SelectOption[] = sysFonts.grouped.value.map((g) => ({ label: g.family, value: g.family }))
  return [
    { type: 'group', label: '预设字体', key: 'builtin', children: builtin.filter((o) => o.value !== '') },
    { type: 'group', label: `电脑系统字体（${sysFonts.count.value}）`, key: 'system', children: sysOpts },
    { label: '系统默认', value: '' },
  ]
})

function onFontChange(family: string): void {
  if (!family) {
    editor.chain().focus().unsetFontFamily().run()
  } else {
    editor.chain().focus().setFontFamily(family).run()
  }
  refreshFont()
}

type ToolButton = {
  key: string
  label?: string
  icon?: string
  title: string
  active: () => boolean
  run: () => void
}

const tools: ToolButton[] = [
  {
    key: 'bold',
    icon: 'i-carbon-text-bold',
    title: '加粗',
    active: () => editor.isActive('bold'),
    run: () => editor.chain().focus().toggleBold().run(),
  },
  {
    key: 'italic',
    icon: 'i-carbon-text-italic',
    title: '斜体',
    active: () => editor.isActive('italic'),
    run: () => editor.chain().focus().toggleItalic().run(),
  },
  {
    key: 'underline',
    icon: 'i-carbon-text-underline',
    title: '下划线',
    active: () => editor.isActive('underline'),
    run: () => editor.chain().focus().toggleUnderline().run(),
  },
  {
    key: 'h2',
    label: 'H2',
    title: '二级标题',
    active: () => editor.isActive('heading', { level: 2 }),
    run: () => editor.chain().focus().toggleHeading({ level: 2 }).run(),
  },
  {
    key: 'h3',
    label: 'H3',
    title: '三级标题',
    active: () => editor.isActive('heading', { level: 3 }),
    run: () => editor.chain().focus().toggleHeading({ level: 3 }).run(),
  },
  {
    key: 'ul',
    icon: 'i-carbon-list-bulleted',
    title: '无序列表',
    active: () => editor.isActive('bulletList'),
    run: () => editor.chain().focus().toggleBulletList().run(),
  },
  {
    key: 'ol',
    icon: 'i-carbon-list-numbered',
    title: '有序列表',
    active: () => editor.isActive('orderedList'),
    run: () => editor.chain().focus().toggleOrderedList().run(),
  },
  {
    key: 'blockquote',
    label: '❝',
    title: '引用',
    active: () => editor.isActive('blockquote'),
    run: () => editor.chain().focus().toggleBlockquote().run(),
  },
  {
    key: 'undo',
    icon: 'i-carbon-undo',
    title: '撤销',
    active: () => false,
    run: () => editor.chain().focus().undo().run(),
  },
  {
    key: 'redo',
    icon: 'i-carbon-redo',
    title: '重做',
    active: () => false,
    run: () => editor.chain().focus().redo().run(),
  },
]
</script>

<template>
  <div class="rt-editor">
    <div class="rt-toolbar">
      <NSelect
        size="tiny"
        :value="currentFont"
        :options="FONT_OPTIONS"
        class="rt-font-select"
        placeholder="字体"
        @update:value="onFontChange"
      />
      <NButton
        v-for="t in tools"
        :key="t.key"
        size="tiny"
        quaternary
        :type="t.active() ? 'primary' : 'default'"
        :title="t.title"
        @click="t.run()"
      >
        <div v-if="t.icon" :class="t.icon" class="text-13px" />
        <span v-else class="text-12px font-bold">{{ t.label }}</span>
      </NButton>
    </div>
    <div class="rt-body">
      <EditorContent :editor="editor" class="rt-content" />
    </div>
  </div>
</template>

<style scoped>
.rt-editor {
  display: flex;
  flex-direction: column;
  gap: 6px;
}
.rt-toolbar {
  display: flex;
  flex-wrap: wrap;
  gap: 2px;
  align-items: center;
}
.rt-font-select {
  width: 108px;
  margin-right: 4px;
}
.rt-body {
  border: 1px solid var(--brand-border);
  border-radius: 6px;
  background: var(--brand-surface);
}
.rt-body:focus-within {
  border-color: var(--brand-primary);
}
/* tiptap 内部 DOM 无 scoped 属性，需 :deep 命中 */
.rt-content :deep(.tiptap) {
  min-height: 160px;
  max-height: 260px;
  overflow-y: auto;
  padding: 8px 10px;
  outline: none;
  font-size: 13px;
  line-height: 1.6;
  color: var(--brand-text-1);
}
.rt-content :deep(.tiptap p) {
  margin: 0.4em 0;
}
.rt-content :deep(.tiptap h1),
.rt-content :deep(.tiptap h2),
.rt-content :deep(.tiptap h3) {
  margin: 0.5em 0 0.3em;
  font-weight: 600;
}
.rt-content :deep(.tiptap ul),
.rt-content :deep(.tiptap ol) {
  padding-left: 1.4em;
  margin: 0.4em 0;
}
.rt-content :deep(.tiptap blockquote) {
  margin: 0.4em 0;
  padding-left: 0.8em;
  border-left: 3px solid var(--brand-border);
  color: var(--brand-text-3);
}
.rt-content :deep(.tiptap:focus) {
  outline: none;
}
</style>

// designer-react/src/panels/props/RichTextEditor.tsx
/**
 * RichTextEditor —— 富文本编辑器（tiptap v3 + StarterKit + 字体扩展，React.lazy 懒加载）
 * 由 RichTextProps 通过 React.lazy 引入，未选中富文本时不加载 tiptap。
 * 对齐 Vue 版 RichTextEditor.vue：字体下拉（预设 + 电脑系统字体分组）+ 工具条 + 编辑区。
 */
import { useEffect, useMemo, useState } from 'react'
import { Editor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'
import { TextStyle } from '@tiptap/extension-text-style'
import { FontFamily } from '@tiptap/extension-font-family'
import { Button, Select } from 'antd'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '../../hooks/useSystemFonts'
import './rich-text-editor.css'

interface Props {
  value?: string
  onChange: (html: string) => void
}

interface ToolButton {
  key: string
  label?: string
  title: string
  active: (editor: Editor) => boolean
  run: (editor: Editor) => void
}

const TOOLS: ToolButton[] = [
  { key: 'bold', label: 'B', title: '加粗', active: (e) => e.isActive('bold'), run: (e) => e.chain().focus().toggleBold().run() },
  { key: 'italic', label: 'I', title: '斜体', active: (e) => e.isActive('italic'), run: (e) => e.chain().focus().toggleItalic().run() },
  { key: 'underline', label: 'U', title: '下划线', active: (e) => e.isActive('underline'), run: (e) => e.chain().focus().toggleUnderline().run() },
  { key: 'h2', label: 'H2', title: '二级标题', active: (e) => e.isActive('heading', { level: 2 }), run: (e) => e.chain().focus().toggleHeading({ level: 2 }).run() },
  { key: 'h3', label: 'H3', title: '三级标题', active: (e) => e.isActive('heading', { level: 3 }), run: (e) => e.chain().focus().toggleHeading({ level: 3 }).run() },
  { key: 'ul', label: '• 列表', title: '无序列表', active: (e) => e.isActive('bulletList'), run: (e) => e.chain().focus().toggleBulletList().run() },
  { key: 'ol', label: '1. 列表', title: '有序列表', active: (e) => e.isActive('orderedList'), run: (e) => e.chain().focus().toggleOrderedList().run() },
  { key: 'blockquote', label: '❝', title: '引用', active: (e) => e.isActive('blockquote'), run: (e) => e.chain().focus().toggleBlockquote().run() },
  { key: 'undo', label: '↩', title: '撤销', active: () => false, run: (e) => e.chain().focus().undo().run() },
  { key: 'redo', label: '↪', title: '重做', active: () => false, run: (e) => e.chain().focus().redo().run() },
]

export default function RichTextEditor({ value, onChange }: Props) {
  const sysFonts = useSystemFonts()

  const editor = useMemo(
    () =>
      new Editor({
        extensions: [StarterKit, TextStyle, FontFamily],
        content: value ?? '',
        // 外部改动与内部编辑统一走 onUpdate；防死循环靠 setContent emitUpdate:false
        onUpdate: ({ editor: ed }) => onChange(ed.getHTML()),
      }),
    // 编辑器实例只随挂载创建一次（对齐 Vue 版行为）
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [],
  )

  /** 外部改动（撤销/加载模板/重置）→ 回写编辑器；emitUpdate:false 避免触发 onUpdate 死循环 */
  useEffect(() => {
    if (value !== undefined && value !== editor.getHTML()) {
      editor.commands.setContent(value ?? '', { emitUpdate: false })
    }
  }, [value, editor])

  useEffect(() => {
    return () => editor.destroy()
  }, [editor])

  /** 编辑器当前字体族（textStyle mark 上）；transaction/selectionUpdate 后刷新 */
  const [currentFont, setCurrentFont] = useState('')
  useEffect(() => {
    const refresh = (): void => {
      setCurrentFont((editor.getAttributes('textStyle').fontFamily as string | undefined) ?? '')
    }
    editor.on('selectionUpdate', refresh)
    editor.on('transaction', refresh)
    refresh()
    return () => {
      editor.off('selectionUpdate', refresh)
      editor.off('transaction', refresh)
    }
  }, [editor, value])

  const fontOptions = useMemo(() => {
    const builtin = [
      ...FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })),
    ]
    if (!sysFonts.ready) return [{ label: '系统默认', value: '' }, ...builtin]
    return [
      { label: '预设字体', title: 'group', options: builtin } as const,
      {
        label: `电脑系统字体（${sysFonts.count}）`,
        title: 'group',
        options: sysFonts.grouped.map((g) => ({ label: g.family, value: g.family })),
      } as const,
      { label: '系统默认', value: '' },
    ]
  }, [sysFonts.ready, sysFonts.count, sysFonts.grouped])

  const onFontChange = (family: string): void => {
    if (!family) {
      editor.chain().focus().unsetFontFamily().run()
    } else {
      editor.chain().focus().setFontFamily(family).run()
    }
    setCurrentFont((editor.getAttributes('textStyle').fontFamily as string | undefined) ?? '')
  }

  return (
    <div className="rt-editor">
      <div className="rt-toolbar">
        <Select
          size="small"
          value={currentFont}
          options={fontOptions as never}
          className="rt-font-select"
          placeholder="字体"
          popupMatchSelectWidth={false}
          onChange={onFontChange}
        />
        {TOOLS.map((t) => (
          <Button
            key={t.key}
            size="small"
            type={t.active(editor) ? 'primary' : 'text'}
            title={t.title}
            className="rt-tool-btn"
            onClick={() => t.run(editor)}
          >
            <span className="rt-tool-label">{t.label}</span>
          </Button>
        ))}
      </div>
      <div className="rt-body">
        <EditorContent editor={editor} className="rt-content" />
      </div>
    </div>
  )
}
