// openprint/src/design/panels/props/TextProps.vue
<script setup lang="ts">
/**
 * TextProps —— 文本控件属性（§5.2/§5.3）：内容（静态/绑定/表达式）+ 排版样式
 */
import { computed } from 'vue'
import {
  NInput,
  NInputNumber,
  NSelect,
  NColorPicker,
  NRadioGroup,
  NRadioButton,
  NButton,
} from 'naive-ui'
import type { SelectOption, SelectGroupOption } from 'naive-ui'
import type { CellFormat, CellFormatKind, TextControl, TextStyle } from '@/types/control'
import { useDesignerStore } from '@/design/stores/designer'
import { useDataSourceStore } from '@/design/stores/dataSource'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '@/design/composables/useSystemFonts'
import ContentValueEditor from './ContentValueEditor.vue'
import type { ContentMode } from './ContentValueEditor.vue'
import {
  formatKindOptions,
  datePatternOptions,
  currencyCodeOptions,
  makeFormat,
  needsPattern,
  needsDigits,
  needsCode,
  supportsThousands,
  suggestKindByFieldType,
} from '@/design/format-options'
import {
  contentModePatch,
  formatHint as formatHintOf,
  formatKindFirstPatch,
  formatPatch,
  isPresetDatePattern as sharedIsPresetDatePattern,
  resolveContentMode,
} from './shared/panel-logic'

const store = useDesignerStore()
const control = computed(() => store.selectedControl as TextControl | null)
const ds = useDataSourceStore()

/** 字体下拉选项（内置预设 + 连接客户端后的电脑系统字体分组） */
const sysFonts = useSystemFonts()

const fontOptions = computed<(SelectOption | SelectGroupOption)[]>(() => {
  const builtin: SelectOption[] = [
    { label: '系统默认', value: '' },
    ...FONT_CATALOG.map((f) => ({ label: f.label, value: f.family })),
  ]
  // 客户端未连接 → 不展示电脑系统字体分组（避免下拉里出现一堆客户端不可达的字体）
  if (!sysFonts.ready.value) return builtin
  const sysOpts: SelectOption[] = sysFonts.grouped.value.map((g) => ({ label: g.family, value: g.family }))
  return [
    { type: 'group', label: '预设字体', key: 'builtin', children: builtin.filter((o) => o.value !== '') },
    { type: 'group', label: `电脑系统字体（${sysFonts.count.value}）`, key: 'system', children: sysOpts },
    { label: '系统默认', value: '' },
  ]
})

function patch(p: Record<string, unknown>): void {
  if (control.value) store.updateControl(control.value.id, p)
}

function patchStyle(p: Partial<TextStyle>): void {
  if (!control.value) return
  patch({ style: { ...control.value.style, ...p } }) // 语义见 shared/panel-logic.mergeStyle
}

/** B / I / U 三键：加粗 / 斜体 / 下划线（切换式） */
const isBold = computed(() => (control.value?.style?.fontWeight ?? 'normal') === 'bold')
const isItalic = computed(() => (control.value?.style?.fontStyle ?? 'normal') === 'italic')
const isUnderline = computed(() => (control.value?.style?.textDecoration ?? 'none') === 'underline')
function toggleBold(): void {
  patchStyle({ fontWeight: isBold.value ? 'normal' : 'bold' })
}
function toggleItalic(): void {
  patchStyle({ fontStyle: isItalic.value ? 'normal' : 'italic' })
}
function toggleUnderline(): void {
  patchStyle({ textDecoration: isUnderline.value ? 'none' : 'underline' })
}

/** 内容类型：固定值 / 变量（字段绑定） / 表达式（显式 contentType 判别，兼容老模板回退） */
const contentMode = computed<ContentMode>(() => resolveContentMode(control.value))

/** 模式切换：写 contentType + 清空其它两个字段（默认值由 ContentValueEditor 注入） */
function onModeChange(m: ContentMode): void {
  patch(contentModePatch(m))
}

/* -------------------------------- 数据格式 -------------------------------- */
/* 仅绑定模式生效：expression 模式请用 {{field | date:'...'}} 过滤器，不在此重复设置。 */

const textFormat = computed<CellFormat>(() => control.value?.format ?? { kind: 'none' })

/** 绑定字段在数据源里的类型（用于提示选哪种格式） */
const boundFieldType = computed(() => {
  const path = control.value?.binding
  if (!path) return undefined
  const f = ds.flatFields.find((x) => x.path === path)
  return f?.type
})
const formatHint = computed(() => formatHintOf(boundFieldType.value))

function patchFormat(fmt: CellFormat): void {
  patch({ format: formatPatch(fmt) })
}
function setFormatKind(kind: CellFormatKind): void {
  patch({ format: formatKindFirstPatch(control.value?.format, kind) })
}
const isPresetDatePattern = sharedIsPresetDatePattern
</script>

<template>
  <div v-if="control" class="props-section">
    <div class="props-title">内容设置</div>

    <ContentValueEditor
      :mode="contentMode"
      :value="control.value ?? ''"
      :binding="control.binding ?? ''"
      :expression="control.expression ?? ''"
      placeholder="文本内容"
      fixed-default="文本"
      binding-default="order.orderNo"
      :expression-default="'{{order.total}}'"
      @update:mode="onModeChange"
      @update:value="patch({ value: $event })"
      @update:binding="patch({ binding: $event })"
      @update:expression="patch({ expression: $event || undefined })"
    />

    <div v-if="contentMode === 'variable'" class="props-section">
      <div class="props-title">数据格式</div>

      <div v-if="formatHint" class="props-tip">{{ formatHint }}</div>

      <div class="props-row">
        <span class="props-label">类型</span>
        <NSelect
          size="small"
          :value="textFormat.kind"
          :options="formatKindOptions"
          @update:value="setFormatKind"
        />
      </div>

      <div v-if="needsPattern(textFormat.kind)" class="props-row">
        <span class="props-label">日期模板</span>
        <NSelect
          size="small"
          :value="isPresetDatePattern(textFormat.pattern) ? textFormat.pattern : '__custom__'"
          :options="datePatternOptions"
          @update:value="
            (v: string) => {
              if (v !== '__custom__') patchFormat({ ...textFormat, kind: 'date', pattern: v })
            }
          "
        />
      </div>
      <div v-if="needsPattern(textFormat.kind) && !isPresetDatePattern(textFormat.pattern)" class="props-row">
        <span class="props-label">自定义</span>
        <NInput
          size="small"
          :value="textFormat.pattern ?? 'YYYY-MM-DD'"
          placeholder="YYYY-MM-DD HH:mm"
          @update:value="(v: string) => patchFormat({ ...textFormat, kind: 'date', pattern: v || 'YYYY-MM-DD' })"
        />
      </div>

      <div v-if="needsDigits(textFormat.kind)" class="props-row">
        <span class="props-label">小数位</span>
        <NInputNumber
          size="small"
          button-placement="both"
          :value="textFormat.digits ?? 2"
          :min="0"
          :max="6"
          :precision="0"
          @update:value="(v: number | null) => patchFormat({ ...textFormat, digits: v ?? 0 })"
        />
      </div>

      <div v-if="needsCode(textFormat.kind)" class="props-row">
        <span class="props-label">币种</span>
        <NSelect
          size="small"
          :value="textFormat.code ?? 'CNY'"
          :options="currencyCodeOptions"
          @update:value="(v: string) => patchFormat({ ...textFormat, kind: 'currency', code: v })"
        />
      </div>

      <div v-if="supportsThousands(textFormat.kind)" class="props-row">
        <span class="props-label">千分位</span>
        <NRadioGroup
          size="small"
          :value="textFormat.thousands === false ? 'off' : 'on'"
          @update:value="(v: string) => patchFormat({ ...textFormat, thousands: v === 'on' })"
        >
          <NRadioButton value="on">开</NRadioButton>
          <NRadioButton value="off">关</NRadioButton>
        </NRadioGroup>
      </div>

      <NButton size="tiny" quaternary @click="patch({ format: undefined })">清除格式</NButton>
    </div>
  </div>

  <div v-if="control" class="props-section">
    <div class="props-title">排版设置</div>

    <div class="grid grid-cols-2 gap-2">
      <div class="props-row">
        <span class="props-label">字号</span>
        <NInputNumber
          size="small"
          button-placement="both"
          :value="control.style?.fontSize ?? 12"
          :min="6"
          :max="72"
          :precision="1"
          @update:value="patchStyle({ fontSize: $event ?? 12 })"
        />
      </div>
      <div class="props-row">
        <span class="props-label">行高</span>
        <NInputNumber
          size="small"
          button-placement="both"
          :value="control.style?.lineHeight ?? 1.16"
          :min="0.8"
          :max="4"
          :step="0.05"
          :precision="2"
          @update:value="patchStyle({ lineHeight: $event ?? 1.16 })"
        />
      </div>
    </div>

    <div class="props-row">
      <span class="props-label">样式</span>
      <div class="flex items-center gap-1">
        <NButton size="small" :type="isBold ? 'primary' : 'default'" title="加粗" @click="toggleBold"><b>B</b></NButton>
        <NButton size="small" :type="isItalic ? 'primary' : 'default'" title="斜体" @click="toggleItalic"><i>I</i></NButton>
        <NButton size="small" :type="isUnderline ? 'primary' : 'default'" title="下划线" @click="toggleUnderline"><u>U</u></NButton>
      </div>
    </div>

    <div class="props-row">
      <span class="props-label">对齐</span>
      <NRadioGroup
        size="small"
        :value="control.style?.textAlign ?? 'left'"
        @update:value="patchStyle({ textAlign: $event })"
      >
        <NRadioButton value="left">左</NRadioButton>
        <NRadioButton value="center">中</NRadioButton>
        <NRadioButton value="right">右</NRadioButton>
      </NRadioGroup>
    </div>

    <div class="props-row">
      <span class="props-label">字体</span>
      <NSelect
        size="small"
        :value="control.style?.fontFamily ?? ''"
        :options="fontOptions"
        placeholder="系统默认"
        filterable
        @update:value="patchStyle({ fontFamily: $event || undefined })"
      />
    </div>

    <div class="props-row">
      <span class="props-label">颜色</span>
      <NColorPicker
        size="small"
        :modes="['hex']"
        :value="control.style?.fill ?? '#000000'"
        :swatches="['#000000', '#333333', '#666666', '#999999', '#1677FF', '#F5222D']"
        @update:value="patchStyle({ fill: $event })"
      />
    </div>

    <div class="props-row">
      <span class="props-label">字距</span>
      <NInputNumber
        size="small"
        button-placement="both"
        :value="control.style?.letterSpacing ?? 0"
        :step="0.5"
        :precision="1"
        @update:value="patchStyle({ letterSpacing: $event ?? 0 })"
      />
    </div>
  </div>
</template>

// designer-react/src/panels/props/TextProps.tsx
/**
 * TextProps —— 文本控件属性面板（React 版）
 *
 * 与 Vue 版 `panels/props/TextProps.vue` 行为一致：内容三态 + 数据格式 + 排版样式。
 * 业务决策（模式判别/切换、格式补丁、样式合并）全部来自**共享的 panel-logic**，
 * 本组件只负责渲染与把 patch 交给 store —— 两端行为漂移在逻辑层被物理杜绝。
 *
 * P3.1 裁剪：字体下拉暂只含「预设字体」（系统字体运行时 core/fonts/system.ts
 * 仍依赖 vue，P3.2 迁移后接入）。
 */
import { Button, ColorPicker, InputNumber, Radio, Select } from 'antd'
import type { RadioChangeEvent } from 'antd'
import type { TextControl, TextStyle } from '@/types/control'
import { FONT_CATALOG } from '@/core/fonts/catalog'
import { useSystemFonts } from '../../hooks/useSystemFonts'
import {
  currencyCodeOptions,
  datePatternOptions,
  formatKindOptions,
  needsCode,
  needsDigits,
  needsPattern,
  supportsThousands,
} from '@/design/format-options'
import {
  contentModePatch,
  formatHint as formatHintOf,
  formatKindFirstPatch,
  formatPatch,
  isPresetDatePattern,
  mergeStyle,
  resolveContentMode,
  type ContentMode,
} from '@/design/panels/props/shared/panel-logic'
import { useDesignerStore } from '../../stores/designer'
import { selectActiveFields, useDataSourceStore } from '../../stores/dataSource'
import { useSelectedControl } from '../../stores/selectors'
import ContentValueEditor from './ContentValueEditor'

/** 颜色快选（与 Vue 版 swatches 一致） */
const SWATCHES = ['#000000', '#333333', '#666666', '#999999', '#1677FF', '#F5222D']

export default function TextProps() {
  const control = useSelectedControl() as TextControl | null

  if (!control) return null

  const updateControl = useDesignerStore.getState().updateControl
  const patch = (p: Record<string, unknown>): void => updateControl(control.id, p)
  const patchStyle = (p: Partial<TextStyle>): void => {
    patch({ style: mergeStyle(control, p).style })
  }

  /* ---------- 内容模式 ---------- */
  const contentMode = resolveContentMode(control)
  const onModeChange = (m: ContentMode): void => patch(contentModePatch(m))

  /* ---------- 数据格式 ---------- */
  const textFormat = control.format ?? { kind: 'none' as const }
  // 绑定字段在数据源里的类型 → 建议文案（字段列表低频变化，此处直接读即可）
  const boundFieldType = control.binding
    ? selectActiveFields(useDataSourceStore.getState()).find((f) => f.path === control.binding)
        ?.type
    : undefined
  const hint = formatHintOf(boundFieldType)

  const patchFormat = (fmt: typeof textFormat): void => patch({ format: formatPatch(fmt) })

  /* ---------- 样式 ---------- */
  const style = control.style ?? {}
  const isBold = (style.fontWeight ?? 'normal') === 'bold'
  const isItalic = (style.fontStyle ?? 'normal') === 'italic'
  const isUnderline = (style.textDecoration ?? 'none') === 'underline'

  // 字体下拉：预设 + 电脑系统字体（打印客户端连接时出现分组，对齐 Vue 版）
  const sysFonts = useSystemFonts()
  const builtinFonts = FONT_CATALOG.map((f) => ({ label: f.label, value: f.family }))
  const fontOptions = sysFonts.ready
    ? [
        { label: '预设字体', title: 'group', options: builtinFonts },
        {
          label: `电脑系统字体（${sysFonts.count}）`,
          title: 'group',
          options: sysFonts.grouped.map((g) => ({ label: g.family, value: g.family })),
        },
        { label: '系统默认', value: '' },
      ]
    : [{ label: '系统默认', value: '' }, ...builtinFonts]

  return (
    <>
      <div className="props-section">
        <div className="props-title">内容设置</div>

        <ContentValueEditor
          mode={contentMode}
          value={control.value ?? ''}
          binding={control.binding ?? ''}
          expression={control.expression ?? ''}
          placeholder="文本内容"
          fixedDefault="文本"
          bindingDefault="order.orderNo"
          expressionDefault="{{order.total}}"
          onModeChange={onModeChange}
          onValueChange={(v) => patch({ value: v })}
          onBindingChange={(v) => patch({ binding: v })}
          onExpressionChange={(v) => patch({ expression: v || undefined })}
        />

        {contentMode === 'variable' && (
          <div className="props-section">
            <div className="props-title">数据格式</div>
            {hint && <div className="props-tip">{hint}</div>}

            <div className="props-row">
              <span className="props-label">类型</span>
              <Select
                size="small"
                value={textFormat.kind}
                options={formatKindOptions}
                onChange={(kind) => patch({ format: formatKindFirstPatch(control.format, kind) })}
              />
            </div>

            {needsPattern(textFormat.kind) && (
              <div className="props-row">
                <span className="props-label">日期模板</span>
                <Select
                  size="small"
                  value={isPresetDatePattern(textFormat.pattern) ? textFormat.pattern : '__custom__'}
                  options={datePatternOptions}
                  onChange={(v) => {
                    if (v !== '__custom__') patchFormat({ ...textFormat, kind: 'date', pattern: v })
                  }}
                />
              </div>
            )}
            {needsPattern(textFormat.kind) && !isPresetDatePattern(textFormat.pattern) && (
              <div className="props-row">
                <span className="props-label">自定义</span>
                <input
                  className="props-input"
                  value={textFormat.pattern ?? 'YYYY-MM-DD'}
                  placeholder="YYYY-MM-DD HH:mm"
                  onChange={(e) =>
                    patchFormat({
                      ...textFormat,
                      kind: 'date',
                      pattern: e.target.value || 'YYYY-MM-DD',
                    })
                  }
                />
              </div>
            )}

            {needsDigits(textFormat.kind) && (
              <div className="props-row">
                <span className="props-label">小数位</span>
                <InputNumber
                  size="small"
                  min={0}
                  max={6}
                  precision={0}
                  value={textFormat.digits ?? 2}
                  onChange={(v) => patchFormat({ ...textFormat, digits: v ?? 0 })}
                />
              </div>
            )}

            {needsCode(textFormat.kind) && (
              <div className="props-row">
                <span className="props-label">币种</span>
                <Select
                  size="small"
                  value={textFormat.code ?? 'CNY'}
                  options={currencyCodeOptions}
                  onChange={(v) => patchFormat({ ...textFormat, kind: 'currency', code: v })}
                />
              </div>
            )}

            {supportsThousands(textFormat.kind) && (
              <div className="props-row">
                <span className="props-label">千分位</span>
                <Radio.Group
                  size="small"
                  value={textFormat.thousands === false ? 'off' : 'on'}
                  optionType="button"
                  options={[
                    { label: '开', value: 'on' },
                    { label: '关', value: 'off' },
                  ]}
                  onChange={(e: RadioChangeEvent) => patchFormat({ ...textFormat, thousands: e.target.value === 'on' })}
                />
              </div>
            )}

            <Button size="small" type="text" onClick={() => patch({ format: undefined })}>
              清除格式
            </Button>
          </div>
        )}
      </div>

      <div className="props-section">
        <div className="props-title">排版设置</div>

        <div className="grid grid-cols-2 gap-2">
          <div className="props-row">
            <span className="props-label">字号</span>
            <InputNumber
              size="small"
              min={6}
              max={72}
              precision={1}
              value={style.fontSize ?? 12}
              onChange={(v) => patchStyle({ fontSize: v ?? 12 })}
            />
          </div>
          <div className="props-row">
            <span className="props-label">行高</span>
            <InputNumber
              size="small"
              min={0.8}
              max={4}
              step={0.05}
              precision={2}
              value={style.lineHeight ?? 1.16}
              onChange={(v) => patchStyle({ lineHeight: v ?? 1.16 })}
            />
          </div>
        </div>

        <div className="props-row">
          <span className="props-label">样式</span>
          <div className="flex items-center gap-1">
            <Button size="small" type={isBold ? 'primary' : 'default'} title="加粗" onClick={() => patchStyle({ fontWeight: isBold ? 'normal' : 'bold' })}>
              <b>B</b>
            </Button>
            <Button size="small" type={isItalic ? 'primary' : 'default'} title="斜体" onClick={() => patchStyle({ fontStyle: isItalic ? 'normal' : 'italic' })}>
              <i>I</i>
            </Button>
            <Button size="small" type={isUnderline ? 'primary' : 'default'} title="下划线" onClick={() => patchStyle({ textDecoration: isUnderline ? 'none' : 'underline' })}>
              <u>U</u>
            </Button>
          </div>
        </div>

        <div className="props-row">
          <span className="props-label">对齐</span>
          <Radio.Group
            size="small"
            value={style.textAlign ?? 'left'}
            optionType="button"
            options={[
              { label: '左', value: 'left' },
              { label: '中', value: 'center' },
              { label: '右', value: 'right' },
            ]}
            onChange={(e: RadioChangeEvent) => patchStyle({ textAlign: e.target.value as TextStyle['textAlign'] })}
          />
        </div>

        <div className="props-row">
          <span className="props-label">字体</span>
          <Select
            size="small"
            showSearch
            value={style.fontFamily ?? ''}
            options={fontOptions}
            placeholder="系统默认"
            onChange={(v) => patchStyle({ fontFamily: v || undefined })}
          />
        </div>

        <div className="props-row">
          <span className="props-label">颜色</span>
          <ColorPicker
            size="small"
            value={style.fill ?? '#000000'}
            // antd 6：色板条以 presets 分组承载（等价 Vue 版 swatches）
            presets={[{ label: '常用', colors: SWATCHES, defaultOpen: true }]}
            onChange={(c) => patchStyle({ fill: c.toHexString() })}
          />
        </div>

        <div className="props-row">
          <span className="props-label">字距</span>
          <InputNumber
            size="small"
            step={0.5}
            precision={1}
            value={style.letterSpacing ?? 0}
            onChange={(v) => patchStyle({ letterSpacing: v ?? 0 })}
          />
        </div>
      </div>
    </>
  )
}
