// openprint/src/design/panels/props/ZoneProps.vue
<script setup lang="ts">
/**
 * ZoneProps —— 页眉/页脚区域控件属性（§5.14.3）：高度 / 每页重复
 * 页码变量 {{page}} / {{pageTotal}} 仅在 zone 内文本生效（渲染期注入）。
 */
import { computed } from 'vue'
import { NInputNumber, NSwitch, NAlert } from 'naive-ui'
import type { ZoneControl } from '@/types/control'
import { useDesignerStore } from '@/design/stores/designer'

const store = useDesignerStore()
const control = computed(() => store.selectedControl as ZoneControl | null)

function patch(p: Record<string, unknown>): void {
  if (control.value) store.updateControl(control.value.id, p)
}
</script>

<template>
  <div v-if="control" class="props-section">
    <div class="props-title">{{ control.zone === 'header' ? '页眉区域' : '页脚区域' }}</div>

    <div class="props-row">
      <span class="props-label" style="min-width: 72px">高度 (mm)</span>
      <NInputNumber
        size="small"
        button-placement="both"
        :value="control.zoneHeight"
        :min="5"
        :max="80"
        :precision="1"
        @update:value="patch({ zoneHeight: $event ?? 20, height: $event ?? 20 })"
      />
    </div>

    <div class="props-row">
      <span class="props-label" style="min-width: 72px">每页重复</span>
      <NSwitch
        size="small"
        :value="control.repeat ?? true"
        @update:value="patch({ repeat: $event })"
      />
    </div>

    <NAlert type="info" :bordered="false" class="text-12px">
      区域内文本支持页码变量：<code v-text="'{{page}}'" /> / <code v-text="'{{pageTotal}}'" />，渲染时自动注入。
      直接把控件拖入色带即可成为子组件。
    </NAlert>
  </div>
</template>

// designer-react/src/panels/props/ZoneProps.tsx
/**
 * ZoneProps —— 页眉/页脚区域控件属性（§5.14.3）：高度 / 每页重复
 * 页码变量 {{page}} / {{pageTotal}} 仅在 zone 内文本生效（渲染期注入）。
 * 与 Vue 版 `panels/props/ZoneProps.vue` 行为一致。
 */
import { Alert, InputNumber, Switch } from 'antd'
import type { ZoneControl } from '@/types/control'
import { useDesignerStore } from '../../stores/designer'
import { useSelectedControl } from '../../stores/selectors'
import '../props.css'

export default function ZoneProps() {
  const control = useSelectedControl() as ZoneControl | null

  if (!control) return null

  const patch = (p: Record<string, unknown>): void =>
    useDesignerStore.getState().updateControl(control.id, p)

  return (
    <div className="props-section">
      <div className="props-title">{control.zone === 'header' ? '页眉区域' : '页脚区域'}</div>

      <div className="props-row">
        <span className="props-label" style={{ minWidth: 72 }}>
          高度 (mm)
        </span>
        <InputNumber
          size="small"
          value={control.zoneHeight}
          min={5}
          max={80}
          precision={1}
          style={{ width: '100%' }}
          onChange={(v) => patch({ zoneHeight: v ?? 20, height: v ?? 20 })}
        />
      </div>

      <div className="props-row">
        <span className="props-label" style={{ minWidth: 72 }}>
          每页重复
        </span>
        <Switch
          size="small"
          checked={control.repeat ?? true}
          onChange={(v) => patch({ repeat: v })}
        />
      </div>

      <Alert
        type="info"
        banner={false}
        style={{ fontSize: 12 }}
        title={
          <span>
            区域内文本支持页码变量：<code>{'{{page}}'}</code> / <code>{'{{pageTotal}}'}</code>
            ，渲染时自动注入。直接把控件拖入色带即可成为子组件。
          </span>
        }
      />
    </div>
  )
}
