// designer-react/src/toolbar/TopToolbar.tsx
/**
 * TopToolbar —— 顶部工具栏（React 版 / antd，56px）
 *
 * 从 Vue 版 `TopToolbar.vue` 迁移（P5.2）。
 * 共享逻辑（文件菜单 / 快捷键指南数据 / 打印状态灯）见
 * `@/design/toolbar/shared/toolbar-logic`（Vue/React 同源，防漂移）。
 *
 * 结构对齐 Vue 版：
 * 左：Logo / 产品名 / 版本(SVIP 开关) / 文件菜单 / 模板市场 / 流水标签 / 后端模式徽标
 * 中：模板名（可随时编辑）
 * 右：撤销重做 / 主题切换 / 边距参考线 / 预览 / 保存 / 导出 / 打印(状态灯) /
 *     JSON / 快捷键指南 / AI / 设置
 *
 * 尚未迁移的弹窗（模板管理 / 设置 / 市场 / 数据导入 / JSON / 打印 / 流水标签 /
 * AI 助手 / 预览 / 导出）以占位 Modal 呈现，P5.3+ 逐个替换。
 */
import { lazy, Suspense, useEffect, useState, type ReactElement } from 'react'
import { Button, Dropdown, Input, Modal, Tooltip, message } from 'antd'
import type { MenuProps } from 'antd'
import logoUrl from '@/assets/logo.png'
import { useDesignerStore } from '../stores/designer'
import { useHistoryStore } from '../stores/history'
import { useUiStore, resolveEffectiveTheme } from '../stores/ui'
import { usePrinterProbeStore } from '../stores/printerProbe'
import {
  createDemoTemplate,
  DEMO_TEMPLATE_NAME,
} from '@/repository/mock/data/demo-template'
import { exportTemplateFile, importTemplateFile } from '@/design/utils/template-file'
import { validateTemplate } from '@/core/spec/validator'
import {
  buildShortcutGroups,
  FILE_MENU_ITEMS,
  isMacPlatform,
  modOf,
  printerDotClass,
  printerTooltip,
  type ShortcutPlatform,
} from '@/design/toolbar/shared/toolbar-logic'
import './top-toolbar.css'
import { ExportDialog } from './ExportDialog'
import { PreviewPanel } from '../preview/PreviewPanel'
import { TemplateModal } from '../modals/TemplateModal'
// Univer 体积大且只在打开报表时才需要，故懒加载：避免拖慢首屏，也避免测试环境被它污染
const GridReportModal = lazy(() => import('../modals/GridReportModal'))
import { DataImportModalInner } from '../modals/DataImportModal'
import { SettingsModal } from '../modals/SettingsModal'
import { AiAssistantModal } from '../modals/AiAssistantModal'
import { PrintDialog } from '../modals/PrintDialog'
import { TemplateMarket } from '../modals/TemplateMarket'
import { JsonViewerModal } from '../modals/JsonViewerModal'
import { FlowLabelModal } from '../modals/FlowLabelModal'
import { confirmDialog } from '../ui-confirm'

/** 待迁移弹窗的占位（P5.3+ 逐个替换为真实实现） */
function PlaceholderDialog({
  title,
  open,
  onClose,
}: {
  title: string
  open: boolean
  onClose: () => void
}): ReactElement {
  return (
    <Modal title={title} open={open} onCancel={onClose} footer={null} width={420}>
      <div className="toolbar-placeholder">「{title}」React 版迁移中（P5.3+）</div>
    </Modal>
  )
}

export default function TopToolbar(): ReactElement {
  /* ------------------------------ store 订阅 ------------------------------ */
  const templateName = useDesignerStore((s) => s.templateName)
  const backendMode = useDesignerStore((s) => s.backendMode)
  const canUndo = useHistoryStore((s) => s.undoStack.length > 0)
  const canRedo = useHistoryStore((s) => s.redoStack.length > 0)
  const themePreference = useUiStore((s) => s.themePreference)
  const systemDark = useUiStore((s) => s.systemDark)
  const showMarginGuides = useUiStore((s) => s.showMarginGuides)
  const printerState = usePrinterProbeStore((s) => s.state)
  const printerHealth = usePrinterProbeStore((s) => s.health)
  const printerCount = usePrinterProbeStore((s) => s.printers.length)
  const printerError = usePrinterProbeStore((s) => s.errorText)
  const printerBase = usePrinterProbeStore((s) => s.baseUrl)

  /* ------------------------------ 本地 UI 状态 ------------------------------ */
  const [showTplModal, setShowTplModal] = useState(false)
  const [showGridReport, setShowGridReport] = useState(false)
  const [showSettings, setShowSettings] = useState(false)
  const [showMarket, setShowMarket] = useState(false)
  const [showDataImport, setShowDataImport] = useState(false)
  const [showJson, setShowJson] = useState(false)
  const [showPrint, setShowPrint] = useState(false)
  const [showFlowLabel, setShowFlowLabel] = useState(false)
  const [showAi, setShowAi] = useState(false)
  const [showShortcuts, setShowShortcuts] = useState(false)
  const [showSaveAs, setShowSaveAs] = useState(false)
  const [saveAsName, setSaveAsName] = useState('')
  const [showNewTemplate, setShowNewTemplate] = useState(false)
  const [newTemplateName, setNewTemplateName] = useState('')

  /** 快捷键指南可手动切换的查看平台；默认跟随当前系统 */
  const [platform, setPlatform] = useState<ShortcutPlatform>(isMacPlatform() ? 'mac' : 'win')

  const isDark = resolveEffectiveTheme({ themePreference, systemDark }) !== 'light'
  const isSvip = resolveEffectiveTheme({ themePreference, systemDark }) === 'svip'
  const shortcutGroups = buildShortcutGroups(modOf(platform))

  /* ------------------------------ 副作用 ------------------------------ */

  // 按 ? 打开快捷键指南（输入框内不触发）
  useEffect(() => {
    const onHelpKey = (e: KeyboardEvent): void => {
      const el = e.target as HTMLElement | null
      const typing =
        !!el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.isContentEditable)
      if (e.key === '?' && !typing) {
        e.preventDefault()
        setShowShortcuts(true)
      }
    }
    window.addEventListener('keydown', onHelpKey)
    return () => window.removeEventListener('keydown', onHelpKey)
  }, [])

  // 启动后静默自测一次打印机连接（失败不打扰用户）
  useEffect(() => {
    void usePrinterProbeStore.getState().probeIfStale()
  }, [])

  /* ------------------------------ 动作 ------------------------------ */

  const onSave = async (): Promise<void> => {
    // 唯一持久化入口（主任定：编辑纯本地，手动保存才写存储；无后端走 localStorage）
    const result = await useDesignerStore.getState().saveTemplate()
    const mode = useDesignerStore.getState().backendMode
    if (result.ok) {
      void message.success(mode === 'cloud' ? '模板已保存到云端' : '模板已保存到本地存储')
    } else {
      void message.error(`保存失败：${result.error}`)
    }
  }

  const onExportTemplate = (): void => {
    const s = useDesignerStore.getState()
    const data = s.buildTemplate()
    const res = validateTemplate(data)
    if (!res.valid) {
      void message.error(`模板校验未通过，无法导出：${res.issues.map((i) => i.message).join('；')}`)
      return
    }
    exportTemplateFile(data, s.templateName)
    void message.success(`已导出：${s.templateName}.json`)
  }

  const onImportTemplate = async (): Promise<void> => {
    const data = await importTemplateFile()
    if (!data) {
      void message.warning('未选择文件或文件读取失败')
      return
    }
    const res = validateTemplate(data)
    if (!res.valid) {
      void message.error(`文件不是有效的模板：${res.issues.map((i) => i.message).join('；')}`)
      return
    }
    const s = useDesignerStore.getState()
    if (s.dirty && !(await confirmDialog('导入将覆盖当前未保存的改动。确定继续？'))) return
    const name = (data as { name?: string }).name || s.templateName || '导入的模板'
    useDesignerStore.getState().loadTemplate({ id: `import-${Date.now()}`, name, data })
    void message.success(`已导入：${name}`)
  }

  const onFileSelect = async (key: string): Promise<void> => {
    const s = useDesignerStore.getState()
    if (key === 'new') {
      if (s.dirty && !(await confirmDialog('当前模板有未保存改动，新建将清空画布。确定继续？')))
        return
      setNewTemplateName('未命名模板')
      setShowNewTemplate(true)
    } else if (key === 'open') {
      setShowTplModal(true)
    } else if (key === 'save') {
      void onSave()
    } else if (key === 'saveAs') {
      setSaveAsName(`${s.templateName} 副本`)
      setShowSaveAs(true)
    } else if (key === 'demo') {
      if (s.dirty && !(await confirmDialog('载入示例模板将覆盖当前未保存的改动。确定继续？')))
        return
      useDesignerStore
        .getState()
        .loadTemplate({ id: 'demo', name: DEMO_TEMPLATE_NAME, data: createDemoTemplate() })
      void message.success(`已载入示例：${DEMO_TEMPLATE_NAME}`)
    } else if (key === 'importTpl') {
      void onImportTemplate()
    } else if (key === 'exportTpl') {
      onExportTemplate()
    } else if (key === 'importData') {
      setShowDataImport(true)
    }
  }

  const confirmNewTemplate = (): void => {
    const name = newTemplateName.trim()
    if (!name) {
      void message.warning('请输入模板名称')
      return
    }
    setShowNewTemplate(false)
    useDesignerStore.getState().newBlankTemplate()
    useDesignerStore.getState().renameTemplate(name, false)
    void message.success(`已新建：${name}`)
  }

  const confirmSaveAs = async (): Promise<void> => {
    const name = saveAsName.trim()
    if (!name) {
      void message.warning('请输入模板名称')
      return
    }
    setShowSaveAs(false)
    const result = await useDesignerStore.getState().saveTemplateAs(name)
    if (result.ok) void message.success(`已另存为：${name}`)
    else void message.error(`另存为失败：${result.error}`)
  }

  const onPrintClick = async (): Promise<void> => {
    setShowPrint(true)
    const ok = await usePrinterProbeStore.getState().probe()
    const st = usePrinterProbeStore.getState()
    if (ok) {
      void message.success(
        `打印客户端已连接：${st.health?.app ?? 'OpenPrint'} v${st.health?.version ?? '?'} · ${
          st.printers.length
        } 台打印机`,
      )
    } else {
      void message.warning(`打印客户端不可达：${st.errorText}`)
    }
  }

  /* ------------------------------ 渲染 ------------------------------ */

  const fileMenuItems: MenuProps['items'] = FILE_MENU_ITEMS.map((item) =>
    item.divider ? { type: 'divider', key: item.key } : { label: item.label, key: item.key },
  )

  return (
    <header className={`toolbar-root ${isDark ? 'dark' : 'light'}`}>
      {/* 左：品牌 + 文件菜单 + 后端模式徽标 */}
      <div className="toolbar-left">
        <div className="logo-circle">
          <img src={logoUrl} alt="OpenPrint" className="logo-img" />
        </div>
        <span className="product-name">OpenPrint</span>
        <Tooltip title={isSvip ? 'SVIP 黑金主题 · 点击退出' : '点击切换 SVIP 黑金主题'}>
          <span
            className={`version-tag${isSvip ? ' is-svip' : ''}`}
            role="button"
            tabIndex={0}
            onClick={() => useUiStore.getState().toggleSvip()}
            onKeyDown={(e) => {
              if (e.key === 'Enter') useUiStore.getState().toggleSvip()
            }}
          >
            {isSvip ? 'SVIP' : 'v2.0.0'}
          </span>
        </Tooltip>

        <Dropdown menu={{ items: fileMenuItems, onClick: ({ key }) => void onFileSelect(key) }}>
          <span className="file-menu-trigger" data-testid="file-menu">
            <span>文件</span>
            <span className="file-menu-caret">▾</span>
          </span>
        </Dropdown>

        <Button
          size="small"
          variant="outlined"
          className="toolbar-ghost-btn"
          onClick={() => setShowMarket(true)}
        >
          模板市场
        </Button>

        <Button
          size="small"
          variant="outlined"
          className="toolbar-ghost-btn"
          data-testid="btn-grid-report"
          onClick={() => setShowGridReport(true)}
        >
          网格报表
        </Button>

        <Button
          size="small"
          variant="outlined"
          className="toolbar-ghost-btn"
          onClick={() => useUiStore.getState().setFlowLabelOpen(true)}
        >
          流水标签
        </Button>

        <Tooltip
          title={
            backendMode === 'cloud'
              ? '已接入后端接口（VITE_OPENPRINT_API_BASE）'
              : '未配置后端，使用本地存储 / 内置 Mock 数据源（主任铁律）'
          }
        >
          <span className={`backend-tag ${backendMode === 'cloud' ? 'is-cloud' : 'is-local'}`}>
            {backendMode === 'cloud' ? '云端' : '本地存储'}
          </span>
        </Tooltip>
      </div>

      {/* 中：模板名（可随时编辑） */}
      <div className="toolbar-center">
        <Input
          size="small"
          value={templateName}
          placeholder="请输入模板名称"
          variant="borderless"
          className="tpl-name-input"
          onChange={(e) => useDesignerStore.getState().renameTemplate(e.target.value)}
        />
      </div>

      {/* 右：操作区 */}
      <div className="toolbar-right">
        <Tooltip title="撤销（Ctrl+Z）">
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="撤销"
            disabled={!canUndo}
            onClick={() => useDesignerStore.getState().undo()}
          >
            ↶
          </Button>
        </Tooltip>
        <Tooltip title="重做（Ctrl+Shift+Z）">
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="重做"
            disabled={!canRedo}
            onClick={() => useDesignerStore.getState().redo()}
          >
            ↷
          </Button>
        </Tooltip>

        <div className="toolbar-sep" />

        <Tooltip
          title={isDark ? '当前深色，点击切浅色' : '当前浅色，点击切深色'}
        >
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="切换主题"
            onClick={() => useUiStore.getState().toggleTheme()}
          >
            {isDark ? '☀' : '☾'}
          </Button>
        </Tooltip>

        <div className="toolbar-sep" />

        <Tooltip title={`页边距参考线：${showMarginGuides ? '显示中' : '已隐藏'}`}>
          <Button
            type={showMarginGuides ? 'primary' : 'text'}
            size="small"
            className="toolbar-icon-btn"
            aria-label="页边距参考线"
            data-narrow-hide
            onClick={() => useUiStore.getState().toggleMarginGuides()}
          >
            ▦
          </Button>
        </Tooltip>

        <div className="toolbar-sep" />

        <Button size="small" variant="outlined" className="toolbar-ghost-btn" onClick={() => useUiStore.getState().setPreviewOpen(true)}>
          预览
        </Button>
        <Button size="small" type="primary" onClick={() => void onSave()}>
          保存
        </Button>
        <Button size="small" variant="outlined" className="toolbar-ghost-btn" onClick={() => useUiStore.getState().setExportOpen(true)}>
          导出
        </Button>

        <Tooltip title={printerTooltip(printerState, {
          app: printerHealth?.app,
          version: printerHealth?.version,
          printerCount,
          errorText: printerError,
          baseUrl: printerBase,
        })}>
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn printer-btn"
            aria-label="打印"
            onClick={() => void onPrintClick()}
          >
            ⎙
            <span className={`printer-dot ${printerDotClass(printerState)}`} />
          </Button>
        </Tooltip>

        <Tooltip title="查看画布 JSON">
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="查看画布 JSON"
            data-narrow-hide
            onClick={() => setShowJson(true)}
          >
            {'</>'}
          </Button>
        </Tooltip>

        <Tooltip title="快捷键指南（?）">
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="快捷键指南"
            data-narrow-hide
            onClick={() => setShowShortcuts(true)}
          >
            ⌨
          </Button>
        </Tooltip>

        <Tooltip title="AI 设计助手">
          <Button
            type="text"
            size="small"
            className="toolbar-icon-btn"
            aria-label="AI 设计助手"
            onClick={() => setShowAi(true)}
          >
            ✦
          </Button>
        </Tooltip>

        <div className="toolbar-sep" />

        <Button
          type="text"
          size="small"
          className="toolbar-icon-btn"
          aria-label="设置"
          onClick={() => setShowSettings(true)}
        >
          ⚙
        </Button>
      </div>

      {/* P5.5 真实现弹窗 */}
      <TemplateModal open={showTplModal} onClose={() => setShowTplModal(false)} />
      {showGridReport && (
        <Suspense fallback={null}>
          <GridReportModal open onClose={() => setShowGridReport(false)} />
        </Suspense>
      )}
      <TemplateMarket open={showMarket} onClose={() => setShowMarket(false)} />
      <JsonViewerModal open={showJson} onClose={() => setShowJson(false)} />

      {/* 预览 / 导出（P5.4 真实现） */}
      <PreviewPanel />
      <ExportDialog />

      {/* 其余待迁移弹窗占位（P5.5+ 替换） */}
      <SettingsModal show={showSettings} onClose={() => setShowSettings(false)} />
      <DataImportModalInner show={showDataImport} onClose={() => setShowDataImport(false)} />
      <PrintDialog show={showPrint} onClose={() => setShowPrint(false)} />
      {/* P5.8 真实现：流水标签批量打印（状态在 ui store，与预览/导出一致） */}
      <FlowLabelModal />
      <AiAssistantModal
        show={showAi}
        onClose={() => setShowAi(false)}
        onOpenSettings={() => {
          setShowAi(false)
          setShowSettings(true)
        }}
      />

      {/* 快捷键指南弹窗 */}
      <Modal
        title="快捷键指南"
        open={showShortcuts}
        onCancel={() => setShowShortcuts(false)}
        footer={null}
        width={560}
      >
        <div className="shortcuts-platform-toggle">
          <button
            type="button"
            className={`platform-tab${platform === 'mac' ? ' active' : ''}`}
            onClick={() => setPlatform('mac')}
          >
            macOS
          </button>
          <button
            type="button"
            className={`platform-tab${platform === 'win' ? ' active' : ''}`}
            onClick={() => setPlatform('win')}
          >
            Windows
          </button>
        </div>
        <div className="shortcuts-body">
          {shortcutGroups.map((group) => (
            <section key={group.title} className="shortcuts-group">
              <h4 className="shortcuts-group-title">{group.title}</h4>
              <ul className="shortcuts-list">
                {group.items.map((item, i) => (
                  <li key={i} className="shortcuts-row">
                    <span className="shortcuts-keys">
                      {item.keys.map((k, ki) => (
                        <span key={ki}>
                          <kbd className="kbd">{k}</kbd>
                          {ki < item.keys.length - 1 && <span className="kbd-plus">+</span>}
                        </span>
                      ))}
                    </span>
                    <span className="shortcuts-desc">
                      {item.desc}
                      {item.hint && <span className="shortcuts-hint">（{item.hint}）</span>}
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          ))}
          <p className="shortcuts-foot">
            提示：在画布任意处按 <kbd className="kbd">?</kbd> 可随时唤起本指南。
          </p>
        </div>
      </Modal>

      {/* 另存为弹窗 */}
      <Modal
        title="另存为"
        open={showSaveAs}
        onCancel={() => setShowSaveAs(false)}
        width={420}
        footer={
          <div className="modal-footer">
            <Button size="small" onClick={() => setShowSaveAs(false)}>
              取消
            </Button>
            <Button size="small" type="primary" onClick={() => void confirmSaveAs()}>
              保存副本
            </Button>
          </div>
        }
      >
        <div className="modal-body">
          <div className="modal-hint">将以新名称保存一份独立副本。</div>
          <Input
            value={saveAsName}
            placeholder="请输入模板名称"
            onChange={(e) => setSaveAsName(e.target.value)}
            onPressEnter={() => void confirmSaveAs()}
          />
        </div>
      </Modal>

      {/* 新建模板弹窗 */}
      <Modal
        title="新建模板"
        open={showNewTemplate}
        onCancel={() => setShowNewTemplate(false)}
        width={420}
        footer={
          <div className="modal-footer">
            <Button size="small" onClick={() => setShowNewTemplate(false)}>
              取消
            </Button>
            <Button size="small" type="primary" onClick={confirmNewTemplate}>
              创建
            </Button>
          </div>
        }
      >
        <div className="modal-body">
          <div className="modal-hint">请输入模板名称，创建空白画布。</div>
          <Input
            value={newTemplateName}
            placeholder="请输入模板名称"
            onChange={(e) => setNewTemplateName(e.target.value)}
            onPressEnter={confirmNewTemplate}
          />
        </div>
      </Modal>
    </header>
  )
}

// openprint/src/design/toolbar/TopToolbar.vue
<script setup lang="ts">
/**
 * TopToolbar —— 顶部工具栏（56px，亮/暗主题用 var(--brand-nav-*) 自适应跟随主题）
 * 左：Logo / 产品名 / 版本 / 文件菜单 / 后端模式徽标；中：模板名 + 保存状态；
 * 右：撤销重做 / 预览 / 保存 / 导出 / 主题切换 / 设置 / 头像。
 */
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import {
  NButton,
  NDropdown,
  NIcon,
  NInput,
  NModal,
  NText,
  NTooltip,
  useMessage,
  type DropdownOption,
} from 'naive-ui'
import { useDesignerStore } from '@/design/stores/designer'
import { useUiStore } from '@/design/stores/ui'
import TemplateModal from '@/design/modals/TemplateModal.vue'
import SettingsModal from '@/design/modals/SettingsModal.vue'
import TemplateMarket from '@/design/modals/TemplateMarket.vue'
import DataImportModal from '@/design/modals/DataImportModal.vue'
import JsonViewerModal from '@/design/modals/JsonViewerModal.vue'
import PrintDialog from '@/design/modals/PrintDialog.vue'
import FlowLabelModal from '@/design/modals/FlowLabelModal.vue'
import PreviewPanel from '@/design/preview/PreviewPanel.vue'
import ExportDialog from '@/design/toolbar/ExportDialog.vue'
import AiAssistantPanel from '@/design/ai/AiAssistantPanel.vue'
import { useConfirm } from '@/design/composables/useConfirm'
import { usePrinterProbe } from '@/design/composables/usePrinterProbe'
import { createDemoTemplate, DEMO_TEMPLATE_NAME } from '@/repository/mock/data/demo-template'
import { exportTemplateFile, importTemplateFile } from '@/design/utils/template-file'
import { validateTemplate } from '@/core/spec/validator'
import {
  buildShortcutGroups,
  FILE_MENU_ITEMS,
  isMacPlatform,
  modOf,
  printerDotClass,
  printerTooltip,
  type ShortcutPlatform,
} from './shared/toolbar-logic'

const store = useDesignerStore()
const uiStore = useUiStore()
const message = useMessage()
const { confirm } = useConfirm()

const showTplModal = ref(false)
const showSaveAs = ref(false)
const showSettings = ref(false)
const showMarket = ref(false)
const showDataImport = ref(false)
const showJson = ref(false)
const showPrint = ref(false)
const showFlowLabel = ref(false)
const showAi = ref(false)
const showNewTemplate = ref(false)
const newTemplateName = ref('')
const saveAsName = ref('')
/** 中间模板名输入框，可随时改名 */
const templateNameRef = ref<{ focus: () => void; select?: () => void } | null>(null)

/** 快捷键指南弹窗 */
const showShortcuts = ref(false)
/** 可手动切换的查看平台；默认跟随当前系统 */
const platform = ref<ShortcutPlatform>(isMacPlatform() ? 'mac' : 'win')
const MOD = computed(() => modOf(platform.value))
const platformLabel = computed(() => (platform.value === 'mac' ? 'macOS' : 'Windows / Linux'))

/** 快捷键数据随所选平台重算（MOD 取自当前平台） */
const shortcutGroups = computed(() => buildShortcutGroups(MOD.value))

function isTypingTarget(t: EventTarget | null): boolean {
  const el = t as HTMLElement | null
  return !!el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' || el.isContentEditable)
}

/** 按 ? 也能打开快捷键指南（输入框内不触发） */
function onHelpKey(e: KeyboardEvent): void {
  if (e.key === '?' && !isTypingTarget(e.target)) {
    e.preventDefault()
    showShortcuts.value = true
  }
}

onMounted(() => window.addEventListener('keydown', onHelpKey))
onBeforeUnmount(() => window.removeEventListener('keydown', onHelpKey))

/* --------------------------- 打印机连接自测 --------------------------- */

const {
  state: printerState,
  printers: printerList,
  health: printerHealth,
  errorText: printerError,
  baseUrl: printerBase,
  probe: runPrinterProbe,
  probeIfStale: runPrinterProbeIfStale,
} = usePrinterProbe()

/** 状态灯颜色：绿=已连接 / 红=不可达 / 黄=检测中 / 灰=未检测 */
const printerDotClassComputed = computed(() => printerDotClass(printerState.value))

/** 悬停提示：版本 + 打印机数量 / 失败原因 */
const printerTooltipComputed = computed(() =>
  printerTooltip(printerState.value, {
    app: printerHealth.value?.app,
    version: printerHealth.value?.version,
    printerCount: printerList.value.length,
    errorText: printerError.value,
    baseUrl: printerBase.value,
  }),
)

/** 启动后静默自测一次，让状态灯有初值（失败不打扰用户） */
onMounted(() => {
  void runPrinterProbeIfStale()
})

/** 点击打印按钮：先自测连接状态，再打开打印弹窗 */
async function onPrintClick(): Promise<void> {
  showPrint.value = true
  const ok = await runPrinterProbe()
  if (ok) {
    message.success(
      `打印客户端已连接：${printerHealth.value?.app ?? 'OpenPrint'} v${
        printerHealth.value?.version ?? '?'
      } · ${printerList.value.length} 台打印机`,
    )
  } else {
    message.warning(`打印客户端不可达：${printerError.value}`)
  }
}

function onTemplateName(v: string): void {
  store.templateName = v
  store.dirty = true
}

const isDark = computed(() => uiStore.effectiveTheme !== 'light')
/** SVIP 黑金主题激活态（版本号点击切换） */
const isSvip = computed(() => uiStore.effectiveTheme === 'svip')

const fileMenuOptions: DropdownOption[] = FILE_MENU_ITEMS.map((item) =>
  item.divider ? { type: 'divider' as const, key: item.key } : { label: item.label, key: item.key },
)

async function onSave(): Promise<void> {
  // 唯一持久化入口（主任定：编辑纯本地，手动保存才写存储；无后端走 localStorage）
  const result = await store.saveTemplate()
  if (result.ok) {
    message.success(store.backendMode === 'cloud' ? '模板已保存到云端' : '模板已保存到本地存储')
  } else {
    message.error(`保存失败：${result.error}`)
  }
}

async function onFileSelect(key: string): Promise<void> {
  if (key === 'new') {
    if (store.dirty && !(await confirm('当前模板有未保存改动，新建将清空画布。确定继续？'))) return
    // 先弹窗让用户输入模板名称
    newTemplateName.value = '未命名模板'
    showNewTemplate.value = true
  } else if (key === 'open') {
    showTplModal.value = true
  } else if (key === 'save') {
    void onSave()
  } else if (key === 'saveAs') {
    saveAsName.value = `${store.templateName} 副本`
    showSaveAs.value = true
  } else if (key === 'demo') {
    if (store.dirty && !(await confirm('载入示例模板将覆盖当前未保存的改动。确定继续？'))) return
    store.loadTemplate({ id: 'demo', name: DEMO_TEMPLATE_NAME, data: createDemoTemplate() })
    message.success(`已载入示例：${DEMO_TEMPLATE_NAME}`)
  } else if (key === 'importTpl') {
    void onImportTemplate()
  } else if (key === 'exportTpl') {
    onExportTemplate()
  } else if (key === 'importData') {
    showDataImport.value = true
  }
}

/** B：导出当前画布模板为 .json 文件 */
function onExportTemplate(): void {
  const data = store.buildTemplate()
  const res = validateTemplate(data)
  if (!res.valid) {
    message.error(`模板校验未通过，无法导出：${res.issues.map((i) => i.message).join('；')}`)
    return
  }
  exportTemplateFile(data, store.templateName)
  message.success(`已导出：${store.templateName}.json`)
}

/** B：从 .json 文件导入模板并载入画布 */
async function onImportTemplate(): Promise<void> {
  const data = await importTemplateFile()
  if (!data) {
    message.warning('未选择文件或文件读取失败')
    return
  }
  const res = validateTemplate(data)
  if (!res.valid) {
    message.error(`文件不是有效的模板：${res.issues.map((i) => i.message).join('；')}`)
    return
  }
  if (store.dirty && !(await confirm('导入将覆盖当前未保存的改动。确定继续？'))) return
  const name = (data as { name?: string }).name || store.templateName || '导入的模板'
  store.loadTemplate({ id: `import-${Date.now()}`, name, data })
  message.success(`已导入：${name}`)
}

/** 确认新建模板：创建空白模板并设置用户输入的名称 */
function confirmNewTemplate(): void {
  const name = newTemplateName.value.trim()
  if (!name) {
    message.warning('请输入模板名称')
    return
  }
  showNewTemplate.value = false
  store.newBlankTemplate()
  store.templateName = name
  store.dirty = false
  message.success(`已新建：${name}`)
}

/** 一键切换（☀ ↔ 🌙）：忽略 system，直接 light/dark 翻转 */
function onToggleTheme(): void {
  uiStore.toggleTheme()
}

/** 点击版本号：SVIP 黑金主题开关 */
function onToggleSvip(): void {
  uiStore.toggleSvip()
}

async function confirmSaveAs(): Promise<void> {
  const name = saveAsName.value.trim()
  if (!name) {
    message.warning('请输入模板名称')
    return
  }
  showSaveAs.value = false
  const result = await store.saveTemplateAs(name)
  if (result.ok) message.success(`已另存为：${name}`)
  else message.error(`另存为失败：${result.error}`)
}

function onPreview(): void {
  uiStore.previewOpen = true
}

function onExport(): void {
  uiStore.exportOpen = true
}
</script>

<script lang="ts">
import { h, type Component } from 'vue'
/** 图标本地函数，避免多一层 import 噪音 */
const IconSun: Component = () =>
  h('div', { class: 'i-carbon-sun text-16px' })
const IconMoon: Component = () =>
  h('div', { class: 'i-carbon-moon text-16px' })
const IconChevronDown: Component = () =>
  h('div', { class: 'i-carbon-chevron-down text-12px' })
</script>

<template>
  <header
    class="toolbar-root flex h-56px items-center justify-between px-4"
    :class="isDark ? 'dark' : 'light'"
  >
    <!-- 左：品牌 + 文件菜单 + 后端模式徽标 -->
    <div class="flex items-center gap-3">
      <div class="logo-circle">
        <img src="@/assets/logo.png" alt="OpenPrint" class="logo-img" />
      </div>
      <span class="product-name">OpenPrint</span>
      <NTooltip>
        <template #trigger>
          <span
            class="version-tag"
            :class="{ 'is-svip': isSvip }"
            role="button"
            tabindex="0"
            @click="onToggleSvip"
            @keydown.enter="onToggleSvip"
          >
            {{ isSvip ? 'SVIP' : 'v2.0.0' }}
          </span>
        </template>
        {{ isSvip ? 'SVIP 黑金主题 · 点击退出' : '点击切换 SVIP 黑金主题' }}
      </NTooltip>

      <NDropdown :options="fileMenuOptions" @select="onFileSelect">
        <span class="file-menu-trigger">
          <span>文件</span>
          <span class="ml-1 inline-flex items-center">
            <n-icon size="14"><IconChevronDown /></n-icon>
          </span>
        </span>
      </NDropdown>

      <!-- 模板市场 -->
      <NButton
        size="small"
        ghost
        class="toolbar-ghost-btn"
        style="margin-left: 8px"
        @click="showMarket = true"
      >
        <div class="i-carbon-store mr-1 text-14px" />
        模板市场
      </NButton>

      <!-- 流水标签批量打印 -->
      <NButton
        size="small"
        ghost
        class="toolbar-ghost-btn"
        style="margin-left: 8px"
        @click="showFlowLabel = true"
      >
        <div class="i-carbon-tag mr-1 text-14px" />
        流水标签
      </NButton>

      <NTooltip>
        <template #trigger>
          <span
            class="backend-tag"
            :class="store.backendMode === 'cloud' ? 'is-cloud' : 'is-local'"
          >
            <div :class="store.backendMode === 'cloud' ? 'i-carbon-cloud' : 'i-carbon-document'" />
            {{ store.backendMode === 'cloud' ? '云端' : '本地存储' }}
          </span>
        </template>
        {{
          store.backendMode === 'cloud'
            ? '已接入后端接口（VITE_OPENPRINT_API_BASE）'
            : '未配置后端，使用本地存储 / 内置 Mock 数据源（主任铁律）'
        }}
      </NTooltip>
    </div>

    <!-- 中：模板名（可随时编辑） -->
    <div class="flex min-w-180px items-center">
      <NInput
        ref="templateNameRef"
        size="small"
        :value="store.templateName"
        placeholder="请输入模板名称"
        :bordered="false"
        class="tpl-name-input"
        @update:value="onTemplateName"
      />
    </div>

    <!-- 右：操作区 -->
    <div class="flex items-center gap-2">
      <!-- 撤销 -->
      <NTooltip>
        <template #trigger>
          <NButton
            quaternary
            size="small"
            class="toolbar-icon-btn"
            :disabled="!store.canUndo"
            @click="store.undo()"
          >
            <div class="i-carbon-undo text-16px" />
          </NButton>
        </template>
        撤销（Ctrl+Z）
      </NTooltip>
      <!-- 重做 -->
      <NTooltip>
        <template #trigger>
          <NButton
            quaternary
            size="small"
            class="toolbar-icon-btn"
            :disabled="!store.canRedo"
            @click="store.redo()"
          >
            <div class="i-carbon-redo text-16px" />
          </NButton>
        </template>
        重做（Ctrl+Shift+Z）
      </NTooltip>

      <div class="toolbar-sep" />

      <!-- 主题一键切换（☀ / 🌙） -->
      <NTooltip>
        <template #trigger>
          <NButton quaternary size="small" class="toolbar-icon-btn" @click="onToggleTheme">
            <div v-if="isDark" class="i-carbon-sun text-16px" />
            <div v-else class="i-carbon-moon text-16px" />
          </NButton>
        </template>
        切换主题：{{ isDark ? '当前深色，点击切浅色' : '当前浅色，点击切深色' }}
      </NTooltip>

      <div class="toolbar-sep" />

      <!-- 页边距参考线开关 -->
      <NTooltip>
        <template #trigger>
          <NButton
            quaternary
            size="small"
            class="toolbar-icon-btn"
            :type="uiStore.showMarginGuides ? 'primary' : 'default'"
            @click="uiStore.toggleMarginGuides()"
          >
            <div class="i-carbon-grid text-16px" />
          </NButton>
        </template>
        页边距参考线：{{ uiStore.showMarginGuides ? '显示中' : '已隐藏' }}
      </NTooltip>

      <div class="toolbar-sep" />

      <NButton size="small" ghost class="toolbar-ghost-btn" @click="onPreview">预览</NButton>
      <NButton size="small" type="primary" @click="onSave">保存</NButton>
      <NButton size="small" ghost class="toolbar-ghost-btn" @click="onExport">导出</NButton>

      <!-- 打印按钮（右上角状态灯：绿=已连接 / 红=不可达 / 黄=检测中 / 灰=未检测） -->
      <NTooltip>
        <template #trigger>
          <NButton
            quaternary
            size="small"
            class="toolbar-icon-btn printer-btn"
            @click="onPrintClick"
          >
            <div class="i-carbon-printer text-16px" />
            <span class="printer-dot" :class="printerDotClass" />
          </NButton>
        </template>
        {{ printerTooltipComputed }}
      </NTooltip>

      <!-- JSON 查看 -->
      <NTooltip>
        <template #trigger>
          <NButton quaternary size="small" class="toolbar-icon-btn" @click="showJson = true">
            <div class="i-carbon-code text-16px" />
          </NButton>
        </template>
        查看画布 JSON
      </NTooltip>

      <!-- 快捷键指南 -->
      <NTooltip>
        <template #trigger>
          <NButton quaternary size="small" class="toolbar-icon-btn" @click="showShortcuts = true">
            <div class="i-carbon-keyboard text-16px" />
          </NButton>
        </template>
        快捷键指南（?）
      </NTooltip>

      <!-- AI 设计助手 -->
      <NTooltip>
        <template #trigger>
          <NButton quaternary size="small" class="toolbar-icon-btn" @click="showAi = true">
            <div class="i-carbon-ai-status text-16px" />
          </NButton>
        </template>
        AI 设计助手
      </NTooltip>

      <div class="toolbar-sep" />

      <NButton quaternary size="small" class="toolbar-icon-btn" @click="showSettings = true">
        <div class="i-carbon-settings text-16px" />
      </NButton>
    </div>

    <!-- 模板管理弹窗 -->
    <TemplateModal v-model:show="showTplModal" />

    <!-- 全局设置弹窗（本地打印 / 远程云打印） -->
    <SettingsModal v-model:show="showSettings" />

    <!-- 模板市场弹窗 -->
    <TemplateMarket v-model:show="showMarket" />

    <!-- 导入数据弹窗 -->
    <DataImportModal v-model:show="showDataImport" />

    <!-- 多页预览面板 -->
    <PreviewPanel v-model:show="uiStore.previewOpen" />

    <!-- 四格式导出对话框 -->
    <ExportDialog v-model:show="uiStore.exportOpen" />

    <!-- JSON 数据查看器 -->
    <JsonViewerModal v-model:show="showJson" />

    <!-- 打印对话框 -->
    <PrintDialog v-model:show="showPrint" />

    <!-- 流水标签批量打印工作台 -->
    <FlowLabelModal v-model:show="showFlowLabel" />

    <!-- AI 设计助手面板 -->
    <AiAssistantPanel v-model:show="showAi" @open-settings="showSettings = true" />

    <!-- 快捷键指南弹窗 -->
    <NModal
      v-model:show="showShortcuts"
      preset="card"
      title="快捷键指南"
      style="width: 560px; max-width: 92vw"
    >
      <template #header-extra>
        <div class="shortcuts-platform-toggle">
          <button
            type="button"
            class="platform-tab"
            :class="{ active: platform === 'mac' }"
            @click="platform = 'mac'"
          >
            macOS
          </button>
          <button
            type="button"
            class="platform-tab"
            :class="{ active: platform === 'win' }"
            @click="platform = 'win'"
          >
            Windows
          </button>
        </div>
      </template>
      <div class="shortcuts-body">
        <section v-for="group in shortcutGroups" :key="group.title" class="shortcuts-group">
          <h4 class="shortcuts-group-title">{{ group.title }}</h4>
          <ul class="shortcuts-list">
            <li v-for="(item, i) in group.items" :key="i" class="shortcuts-row">
              <span class="shortcuts-keys">
                <template v-for="(k, ki) in item.keys" :key="ki">
                  <kbd class="kbd">{{ k }}</kbd>
                  <span v-if="ki < item.keys.length - 1" class="kbd-plus">+</span>
                </template>
              </span>
              <span class="shortcuts-desc">
                {{ item.desc }}
                <span v-if="item.hint" class="shortcuts-hint">（{{ item.hint }}）</span>
              </span>
            </li>
          </ul>
        </section>
        <p class="shortcuts-foot">提示：在画布任意处按 <kbd class="kbd">?</kbd> 可随时唤起本指南。</p>
      </div>
    </NModal>

    <!-- 另存为弹窗 -->
    <NModal
      v-model:show="showSaveAs"
      preset="card"
      title="另存为"
      style="width: 420px; max-width: 92vw"
    >
      <div class="flex flex-col gap-2">
        <NText depth="3" class="text-12px">将以新名称保存一份独立副本。</NText>
        <NInput v-model:value="saveAsName" placeholder="请输入模板名称" @keyup.enter="confirmSaveAs" />
      </div>
      <template #footer>
        <div class="flex justify-end gap-2">
          <NButton size="small" @click="showSaveAs = false">取消</NButton>
          <NButton size="small" type="primary" @click="confirmSaveAs">保存副本</NButton>
        </div>
      </template>
    </NModal>

    <!-- 新建模板弹窗 -->
    <NModal
      v-model:show="showNewTemplate"
      preset="card"
      title="新建模板"
      style="width: 420px; max-width: 92vw"
    >
      <div class="flex flex-col gap-2">
        <NText depth="3" class="text-12px">请输入模板名称，创建空白画布。</NText>
        <NInput
          v-model:value="newTemplateName"
          placeholder="请输入模板名称"
          @keyup.enter="confirmNewTemplate"
        />
      </div>
      <template #footer>
        <div class="flex justify-end gap-2">
          <NButton size="small" @click="showNewTemplate = false">取消</NButton>
          <NButton size="small" type="primary" @click="confirmNewTemplate">创建</NButton>
        </div>
      </template>
    </NModal>
  </header>
</template>

<style scoped>
/* ================= 工具栏 —— 亮/暗都走 CSS 变量，跟随主题 ================= */
.toolbar-root {
  background: var(--brand-nav-bg);
  color: var(--brand-nav-text);
  border-bottom: 1px solid var(--brand-border);
}

/* 品牌 logo —— 保持图片原格式（透明就透明），不加背景色 */
.logo-circle {
  height: 28px;
  width: 28px;
  display: flex;
  align-items: center;
  justify-content: center;
  flex-shrink: 0;
}
.logo-img {
  width: 100%;
  height: 100%;
  object-fit: contain;
  display: block;
}

.product-name {
  font-size: 14px;
  font-weight: 500;
  color: var(--brand-nav-text-active);
}

.version-tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  height: 18px;
  padding: 0 8px;
  font-size: 11px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  line-height: 1;
  letter-spacing: 0.2px;
  color: #fff;
  background: linear-gradient(135deg, var(--brand-primary), color-mix(in srgb, var(--brand-primary) 70%, #0b1c3a));
  border: none;
  border-radius: 999px;
  cursor: pointer;
  user-select: none;
  transition: filter 0.15s;
}
.version-tag:hover {
  filter: brightness(1.15);
}
/* SVIP 黑金激活态：金色渐变文字（#FFB95A → #E4A93C → #B87100）+ 深炭底 + 金描边 */
.version-tag.is-svip {
  color: transparent;
  background: #2b2e31;
  background-image: linear-gradient(135deg, #ffb95a 0%, #e4a93c 55%, #b87100 100%);
  background-clip: text;
  -webkit-background-clip: text;
  border: 1px solid rgba(228, 169, 60, 0.55);
  box-shadow: 0 0 8px rgba(228, 169, 60, 0.25);
  letter-spacing: 0.5px;
}
.version-tag.is-svip:hover {
  filter: brightness(1.2);
}

/* 文件菜单触发器 */
.file-menu-trigger {
  margin-left: 16px;
  cursor: pointer;
  display: inline-flex;
  align-items: center;
  padding: 4px 8px;
  border-radius: 6px;
  font-size: 13px;
  color: var(--brand-nav-icon);
  transition:
    color 0.15s,
    background 0.15s;
}
.file-menu-trigger:hover {
  color: var(--brand-nav-icon-hover);
  background: var(--brand-nav-bg-hover);
}

/* 后端模式徽标 */
.backend-tag {
  display: inline-flex;
  align-items: center;
  gap: 4px;
  padding: 2px 8px;
  border-radius: 6px;
  font-size: 11px;
}
.backend-tag.is-cloud {
  background: rgba(16, 185, 129, 0.15);
  color: #34d399;
}
.backend-tag.is-local {
  background: var(--brand-nav-bg-hover);
  color: var(--brand-nav-text-muted);
}

/* 中间模板名（内联可编辑，去边框呈标题样式） */
.tpl-name-input {
  --n-color: var(--brand-nav-text-active);
  --n-text-color: var(--brand-nav-text-active);
  --n-caret-color: var(--brand-nav-text-active);
  --n-font-size: 14px;
  --n-font-weight: 500;
  --n-padding: 0;
  --n-text-align: center;
  max-width: 200px;
}
.tpl-name-input :deep(.n-input__input-el) {
  text-align: center;
  font-weight: 500;
}

/* 图标按钮（quaternary → 用 nav 配色保证在深色导航上可读） */
.toolbar-icon-btn {
  color: var(--brand-nav-icon) !important;
}
.toolbar-icon-btn:hover:not(:disabled) {
  color: var(--brand-nav-icon-hover) !important;
  background: var(--brand-nav-bg-hover) !important;
}
.toolbar-icon-btn:disabled {
  opacity: 0.4;
}

  /* 幽灵按钮（在深导航上：浅色下 white 边框/文字，暗色下边框同 muted） */
.toolbar-ghost-btn {
  --n-text-color: var(--brand-nav-icon);
  --n-text-color-hover: var(--brand-nav-icon-hover);
  --n-border: 1px solid var(--brand-nav-text-muted);
  --n-border-hover: 1px solid var(--brand-nav-icon-hover);
  --n-color-hover: var(--brand-nav-bg-hover);
}

/* 分隔线 */
.toolbar-sep {
  width: 1px;
  height: 20px;
  margin: 0 4px;
  background: var(--brand-border);
}

/* ================= 快捷键指南弹窗 ================= */
/* 平台分段切换（macOS / Windows 互看） */
.shortcuts-platform-toggle {
  display: inline-flex;
  padding: 2px;
  border-radius: 7px;
  background: var(--brand-bg-hover, rgba(128, 128, 128, 0.12));
  border: 1px solid var(--brand-border, #e5e5e5);
}
.platform-tab {
  appearance: none;
  border: none;
  cursor: pointer;
  font-size: 12px;
  line-height: 1;
  padding: 4px 10px;
  border-radius: 5px;
  color: var(--brand-text-muted, #888);
  background: transparent;
  transition:
    color 0.15s,
    background 0.15s;
}
.platform-tab:hover {
  color: var(--brand-text, #333);
}
.platform-tab.active {
  color: #fff;
  background: var(--brand-primary, #3b82f6);
  font-weight: 600;
}

.shortcuts-body {
  display: flex;
  flex-direction: column;
  gap: 18px;
}

.shortcuts-group-title {
  margin: 0 0 8px;
  font-size: 13px;
  font-weight: 600;
  color: var(--brand-text, inherit);
}

.shortcuts-list {
  margin: 0;
  padding: 0;
  list-style: none;
  display: flex;
  flex-direction: column;
  gap: 6px;
}

.shortcuts-row {
  display: flex;
  align-items: center;
  gap: 12px;
  min-height: 28px;
}

.shortcuts-keys {
  flex-shrink: 0;
  display: inline-flex;
  align-items: center;
  gap: 4px;
  width: 168px;
}

.kbd {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 22px;
  height: 22px;
  padding: 0 7px;
  font-size: 12px;
  font-family: inherit;
  line-height: 1;
  color: var(--brand-text, #333);
  background: var(--brand-bg-hover, #f5f5f5);
  border: 1px solid var(--brand-border, #e0e0e0);
  border-bottom-width: 2px;
  border-radius: 5px;
  box-shadow: 0 1px 0 rgba(0, 0, 0, 0.04);
}

.kbd-plus {
  font-size: 11px;
  color: var(--brand-text-muted, #aaa);
}

.shortcuts-desc {
  font-size: 13px;
  color: var(--brand-text, inherit);
}

.shortcuts-hint {
  font-size: 12px;
  color: var(--brand-text-muted, #999);
}

.shortcuts-foot {
  margin: 4px 0 0;
  font-size: 12px;
  color: var(--brand-text-muted, #999);
  border-top: 1px dashed var(--brand-border, #eee);
  padding-top: 12px;
}

/* ================= 打印按钮连接状态灯 ================= */
.printer-btn {
  position: relative;
}

.printer-dot {
  position: absolute;
  top: 3px;
  right: 3px;
  width: 7px;
  height: 7px;
  border-radius: 50%;
  border: 1px solid var(--brand-nav-bg, #fff);
  background: #9ca3af;
  transition: background 0.2s;
}

.printer-dot.is-connected {
  background: #22c55e;
  box-shadow: 0 0 4px rgba(34, 197, 94, 0.7);
}

.printer-dot.is-disconnected {
  background: #ef4444;
  box-shadow: 0 0 4px rgba(239, 68, 68, 0.7);
}

.printer-dot.is-checking {
  background: #f59e0b;
  animation: printer-dot-pulse 1s ease-in-out infinite;
}

.printer-dot.is-idle {
  background: #9ca3af;
}

@keyframes printer-dot-pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.3;
  }
}
</style>
